import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packDeltaTwoScenarios: ScenarioType[] = [
  { id: 'dtw-01', title: 'Fake Vegan', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Dining', role: 'Judgmental Friend', desc: 'Defend yourself after getting caught eating a bacon cheeseburger while claiming to be vegan.' },
  { id: 'dtw-02', title: 'Dine and Dash Accusation', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Incidents', role: 'Restaurant Manager', desc: 'Prove you already paid the bill in cash and were not trying to run out the door.' },
  { id: 'dtw-03', title: 'Spilled Red Wine', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Incidents', role: 'Wealthy Patron', desc: 'Apologize for knocking a full glass of red wine onto someone\'s white designer jacket.' },
  { id: 'dtw-04', title: 'Bug in the Salad', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Dining', role: 'Skeptical Waiter', desc: 'Demand a refund after finding a very large, very alive bug crawling in your lettuce.' },
  { id: 'dtw-05', title: 'Spicy Challenge Regret', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Dining', role: 'Smug Chef', desc: 'Beg for a gallon of milk after arrogantly attempting the "Death Noodle" spice challenge.' },
  { id: 'dtw-06', title: 'Arguing Over the Tip', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Everyday', role: 'Cheap Friend', desc: 'Argue with your friend who refuses to leave more than a 5% tip for excellent service.' },
  { id: 'dtw-07', title: 'Buffet Limits', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Dining', role: 'Buffet Manager', desc: 'Argue that "All You Can Eat" means you can stay for 6 hours and eat 15 plates of crab legs.' },
  { id: 'dtw-08', title: 'Awkward Birthday Song', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Dining', role: 'Enthusiastic Wait Staff', desc: 'Sit in agonizing silence while five waiters loudly sing you a corporate birthday song.' },
  { id: 'dtw-09', title: 'Fake ID Confiscated', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Incidents', role: 'Bouncer', desc: 'Beg the bouncer to give back your terrible fake ID because it cost you $100.' },
  { id: 'dtw-10', title: 'Dropped Ice Cream', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Dining', role: 'Ice Cream Vendor', desc: 'Ask for a replacement cone after a seagull immediately knocked yours onto the pavement.' },
  { id: 'dtw-11', title: 'Unpronounceable Menu', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Dining', role: 'Pretentious Waiter', desc: 'Struggle to order a dish that is entirely in a language you don\'t speak.' },
  { id: 'dtw-12', title: 'Secret Recipe', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Dining', role: 'Suspicious Chef', desc: 'Try to trick the chef into telling you exactly what is in their secret sauce.' },
  { id: 'dtw-13', title: 'Tiny Portions', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Dining', role: 'Maitre D', desc: 'Complain that you paid $150 and the food on the plate is the size of a golf ball.' },
  { id: 'dtw-14', title: 'Stolen Reservation', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Dining', role: 'Hostess', desc: 'Argue that someone else named "John" clearly stole your 8 PM dinner reservation.' },
  { id: 'dtw-15', title: 'Refusing to Leave', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Dining', role: 'Tired Bartender', desc: 'Try to order one more drink even though the bar lights are fully on and the chairs are stacked.' }
];