import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packNovemberThreeScenarios: ScenarioType[] = [
  { id: 'nt3-01', title: 'Lockpicking Lawyer', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Everyday', role: 'Security Vendor', desc: 'Demonstrate to a vendor that their "unpickable" padlock can be opened in 4 seconds.' },
  { id: 'nt3-02', title: 'Ant Colony Escape', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Incidents', role: 'Panicked Roommate', desc: 'Explain how 10,000 harvester ants managed to escape their formicarium.' },
  { id: 'nt3-03', title: 'Ham Radio Interference', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Tech', role: 'Amateur Operator', desc: 'Argue with an operator who keeps stepping on your frequency during a DX transmission.' },
  { id: 'nt3-04', title: 'Speedcubing Dispute', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Everyday', role: 'Tournament Judge', desc: 'Argue that your 4.2-second Rubik\'s Cube solve was completely legitimate.' },
  { id: 'nt3-05', title: 'Mechanical Watch Repair', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Shopping', role: 'Horologist', desc: 'Complain that the mainspring on your vintage automatic watch was installed backwards.' },
  { id: 'nt3-06', title: 'Bonsai Tree Trimming', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Everyday', role: 'Overzealous Gardener', desc: 'Yell at a landscaper who just took hedge clippers to your 40-year-old Bonsai tree.' },
  { id: 'nt3-07', title: 'HEMA Fencing Foul', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Everyday', role: 'Sword Fighting Referee', desc: 'Argue that your longsword strike clearly hit their mask before they parried.' },
  { id: 'nt3-08', title: 'Miniature Painting Thinning', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Everyday', role: 'Hobby Gatekeeper', desc: 'Defend your technique of not thinning your paints to a Warhammer elitist.' },
  { id: 'nt3-09', title: 'Aquascaping Algae', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Shopping', role: 'Aquarium Store Clerk', desc: 'Demand a refund for a supposedly "algae-eating" snail that is eating your expensive plants.' },
  { id: 'nt3-10', title: 'Vexillology Nerd', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Everyday', role: 'City Council Member', desc: 'Give a passionate 5-minute speech on why the current city flag violates all rules of good design.' },
  { id: 'nt3-11', title: 'Foraging Poison', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Incidents', role: 'Concerned Friend', desc: 'Convince your friend that the glowing mushroom you just ate is definitely safe.' },
  { id: 'nt3-12', title: 'Geocaching Trespass', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Incidents', role: 'Angry Landowner', desc: 'Explain that you are not a burglar, you are just looking for a tiny plastic capsule in the bushes.' },
  { id: 'nt3-13', title: 'Beekeeping Swarm', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Incidents', role: 'Terrified Mail Carrier', desc: 'Assure the mail carrier that the massive swarm of bees on your porch is "perfectly docile."' },
  { id: 'nt3-14', title: 'Glassblowing Burn', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Work', role: 'Studio Instructor', desc: 'Explain how you accidentally fused your glass swan to the metal blowpipe.' },
  { id: 'nt3-15', title: 'Cheese Cave Mold', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Work', role: 'Health Inspector', desc: 'Argue that the terrifying blue fuzz growing on your artisanal cheese is intentional.' }
];