import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packUniformScenarios: ScenarioType[] = [
  { id: 'uni-01', title: 'World of Warships Broadside', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English', 'German'], category: 'Gaming', role: 'Angry Teammate', desc: 'Yell at a battleship captain for showing full broadside and getting instantly deleted.' },
  { id: 'uni-02', title: 'Fallout NV Mod Load Order', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Gaming', role: 'Modding Expert', desc: 'Beg for help fixing your Fallout: New Vegas load order because the game crashes on startup.' },
  { id: 'uni-03', title: 'Devil May Cry Combos', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English', 'Japanese'], category: 'Gaming', role: 'DMC Veteran', desc: 'Argue that achieving an SSS rank in Devil May Cry 5 requires actual skill, not just button mashing.' },
  { id: 'uni-04', title: 'Sekiro Hesitation', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Gaming', role: 'Isshin Ashina', desc: 'Get lectured by a gamer quoting "Hesitation is defeat" after you died to the same boss 20 times.' },
  { id: 'uni-05', title: 'Warframe Void Relics', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Gaming', role: 'Squad Leader', desc: 'Argue over who brought the wrong intact relic to a radiant-only fissure run.' },
  { id: 'uni-06', title: 'Plague Inc. Strategy', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Gaming', role: 'Armchair Scientist', desc: 'Debate why starting your virus in Greenland is a terrible tactical decision.' },
  { id: 'uni-07', title: 'Shadow Fight 3 Loadout', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Gaming', role: 'Rival Player', desc: 'Defend your specific weapon and armor set choice in Shadow Fight 3.' },
  { id: 'uni-08', title: 'World of Tanks Artillery', originalLanguage: 'German', availableLanguages: ['German', 'English', 'Russian'], category: 'Gaming', role: 'Heavy Tank Driver', desc: 'Complain bitterly about getting focused by artillery for the entire match.' },
  { id: 'uni-09', title: 'Asphalt Legends Pay2Win', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Gaming', role: 'Whale Player', desc: 'Argue that Asphalt Legends multiplayer is entirely pay-to-win.' },
  { id: 'uni-10', title: 'Call of Duty Mobile Ping', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Gaming', role: 'Sweaty Opponent', desc: 'Accuse the enemy sniper in CODM of having a massive ping advantage.' },
  { id: 'uni-11', title: 'Shadow Fight 4 Arena', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Gaming', role: 'Spammer', desc: 'Call out a player in SF4 Arena for just backing into the corner and spamming projectiles.' },
  { id: 'uni-12', title: 'Pokémon Fire Red Nuzlocke', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Gaming', role: 'Twitch Chat', desc: 'Mourn the loss of your starter Pokémon due to a random critical hit in a Nuzlocke run.' },
  { id: 'uni-13', title: 'Blood Strike Carry', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Gaming', role: 'Ajxrhaider (You)', desc: 'Explain to your dead squad exactly how you intend to clutch a 1v4 in Blood Strike.' },
  { id: 'uni-14', title: 'Controller Drift', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Tech', role: 'Console Repair', desc: 'Demand a warranty replacement for a controller that has massive stick drift.' },
  { id: 'uni-15', title: 'The Rage Quit', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Everyday', role: 'Concerned Roommate', desc: 'Explain why you just yelled and slammed your desk at 2 AM.' }
];