import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packVictorTwoScenarios: ScenarioType[] = [
  { id: 'vtw-01', title: 'The Sweaty Bench', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Everyday', role: 'Gym Bro', desc: 'Ask the guy who just left the bench press why he didn\'t wipe off his massive puddle of sweat.' },
  { id: 'vtw-02', title: 'Double-Arm Pole Swings', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Everyday', role: 'Confused Trainer', desc: 'Defend your routine of doing exactly 100 double-arm long pole swings in the middle of a commercial gym.' },
  { id: 'vtw-03', title: 'Skipping Leg Day', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Everyday', role: 'Judgmental Friend', desc: 'Argue that your 120 jump routine perfectly compensates for missing leg day.' },
  { id: 'vtw-04', title: 'Pre-Workout Jitters', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Everyday', role: 'Gym Receptionist', desc: 'Explain that you accidentally took three scoops of pre-workout and now you can see sound.' },
  { id: 'vtw-05', title: 'Unsolicited Form Check', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Everyday', role: 'Arrogant Powerlifter', desc: 'Politely tell a stranger that you do not need their advice on your deadlift form.' },
  { id: 'vtw-06', title: 'Broken Treadmill', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Incidents', role: 'Maintenance Worker', desc: 'Explain how the treadmill belt completely snapped while you were sprinting at max speed.' },
  { id: 'vtw-07', title: 'Locker Room Theft', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Incidents', role: 'Gym Manager', desc: 'Report that someone stole your Midnight Black Xiaomi Redmi 15 out of your locker.' },
  { id: 'vtw-08', title: 'The Grunter', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Everyday', role: 'Loud Lifter', desc: 'Ask the person next to you if they could stop screaming every time they lift a 10-pound dumbbell.' },
  { id: 'vtw-09', title: 'Gym Closing Time', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Everyday', role: 'Tired Employee', desc: 'Beg for just five more minutes so you can finish your 60 single-arm short pole swings.' },
  { id: 'vtw-10', title: 'Protein Powder Spill', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Everyday', role: 'Janitor', desc: 'Apologize for dropping an entire 5lb tub of whey protein all over the lobby floor.' },
  { id: 'vtw-11', title: 'Claiming the Rack', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Everyday', role: 'Territorial Lifter', desc: 'Argue that leaving a towel on the squat rack does not reserve it for an hour.' },
  { id: 'vtw-12', title: 'Yoga Mat Dispute', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Everyday', role: 'Yoga Instructor', desc: 'Defend your spot in the back of the class after someone tries to unroll their mat over yours.' },
  { id: 'vtw-13', title: 'Heavy Bag Dominance', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Everyday', role: 'MMA Wannabe', desc: 'Ask the guy lightly tapping the heavy bag if you can actually use it for a real workout.' },
  { id: 'vtw-14', title: 'Forgetting Headphones', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Everyday', role: 'Chatty Member', desc: 'Try to signal that you are working out in silence and do not want to talk.' },
  { id: 'vtw-15', title: 'Expired Membership', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Work', role: 'Front Desk', desc: 'Argue that your auto-pay should have gone through and you demand entry.' }
];