import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packRomeoScenarios: ScenarioType[] = [
  { id: 'rom-01', title: 'The TEFConnect Pitch', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Work', role: 'Venture Capitalist', desc: 'Defend your pre-launch ICT business idea focusing on web design, robotics, and digital media.' },
  { id: 'rom-02', title: 'Voix Network Downtime', originalLanguage: 'English', availableLanguages: ['English', 'Pidgin English'], category: 'Work', role: 'Angry Client', desc: 'Calm a client down while actively merging UptimeRobot logs to find the exact MTTR for a recent outage.' },
  { id: 'rom-03', title: 'Elementor Favicon Bug', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Tech', role: 'WordPress Dev', desc: 'Argue with a plugin developer about why the Voix Talk logo isn\'t rendering correctly on mobile.' },
  { id: 'rom-04', title: 'Domain Transfer Hostage', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Tech', role: 'Affeez Host Rep', desc: 'Demand your auth code so you can migrate your domain to Smartweb immediately.' },
  { id: 'rom-05', title: 'CAC Name Similarity', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Work', role: 'CAC Support Agent', desc: 'Argue that "Hizaki Tech" is entirely unique and should not have failed the Nigerian CAC name reservation.' },
  { id: 'rom-06', title: 'Next.js vs SvelteKit', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Tech', role: 'Svelte Fanatic', desc: 'Defend your decision to rebuild Hizaki Labs using React and Vite instead of SvelteKit.' },
  { id: 'rom-07', title: 'Tailwind CSS Clutter', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Tech', role: 'CSS Purist', desc: 'Explain why utility-first Tailwind classes are actually highly maintainable in a massive codebase.' },
  { id: 'rom-08', title: 'SQLite in Production', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Tech', role: 'PostgreSQL Elitist', desc: 'Argue that SQLite is perfectly fine for the initial Voix ERP backend.' },
  { id: 'rom-09', title: 'NYSC Clearance', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Work', role: 'LGI (Local Govt Inspector)', desc: 'Explain why you missed your monthly biometric clearance at your primary assignment.' },
  { id: 'rom-10', title: 'Git Commit Formats', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Work', role: 'Lead Developer', desc: 'Defend your decision to name all your Git commits after military hardware and special forces units.' },
  { id: 'rom-11', title: 'VS Code Tab Panic', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Tech', role: 'Pair Programmer', desc: 'Apologize for accidentally closing 40 active file tabs in Cursor AI.' },
  { id: 'rom-12', title: 'OneDrive Sync Fail', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Tech', role: 'IT Support', desc: 'Troubleshoot why rclone bisync is aggressively deleting your local files instead of backing them up.' },
  { id: 'rom-13', title: 'ChronoMass Logic', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Tech', role: 'Civil Engineer', desc: 'Pitch the theoretical AI Mass Map framework for simulating 100 years of building structural fatigue.' },
  { id: 'rom-14', title: 'Trauma Engine C++', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Tech', role: 'Legacy Coder', desc: 'Argue why writing a custom 3D engine in C++23 is better than just using Unreal.' },
  { id: 'rom-15', title: 'Otaku Sync Schema', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Tech', role: 'Database Architect', desc: 'Explain how to normalize API payloads from MyAnimeList and Simkl into a single Node.js schema.' }
];