import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packCharlieTwoScenarios: ScenarioType[] = [
  { id: 'ctw-01', title: 'Trapped in Vim', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Tech', role: 'Senior Developer', desc: 'Beg your senior dev for help because you opened Vim and don\'t know how to exit.' },
  { id: 'ctw-02', title: 'Mechanical Keyboard', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Work', role: 'Annoyed Coworker', desc: 'Defend your right to use Cherry MX Blue switches in an open-plan office.' },
  { id: 'ctw-03', title: 'Z-Index Battle', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Tech', role: 'UI Designer', desc: 'Explain why you set the CSS z-index to 9999999 and broke the entire navigation bar.' },
  { id: 'ctw-04', title: 'Forgot Sudo Password', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Tech', role: 'Sysadmin', desc: 'Admit that you forgot the root password to the production server you just provisioned.' },
  { id: 'ctw-05', title: 'Infinite While Loop', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Tech', role: 'Cloud Provider Rep', desc: 'Explain how an infinite loop in your code accidentally spun up 400 virtual machines.' },
  { id: 'ctw-06', title: 'API Rate Limit', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Tech', role: 'API Vendor', desc: 'Plead for an unban after your script accidentally hit their API 50,000 times in ten seconds.' },
  { id: 'ctw-07', title: '1,000 Open Tabs', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Tech', role: 'IT Support', desc: 'Deny that your browser having 1,000 open tabs is the reason your laptop is overheating.' },
  { id: 'ctw-08', title: 'Windows Update Ambush', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Work', role: 'Impatient Client', desc: 'Apologize as your laptop forces a 45-minute Windows Update right in the middle of a pitch.' },
  { id: 'ctw-09', title: 'Water on the Laptop', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Tech', role: 'Genius Bar Tech', desc: 'Swear that you definitely did not spill a glass of water on the motherboard.' },
  { id: 'ctw-10', title: 'Explaining Blockchain', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Everyday', role: 'Confused Grandparent', desc: 'Try to explain what cryptocurrency and the blockchain are to your 80-year-old grandmother.' },
  { id: 'ctw-11', title: 'Broken Git Rebase', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Tech', role: 'Furious Tech Lead', desc: 'Explain how you accidentally rewrote the Git history for the entire repository.' },
  { id: 'ctw-12', title: 'Mouse Double-Clicking', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Shopping', role: 'Customer Service', desc: 'Demand a refund for a gaming mouse that registers two clicks every time you press it once.' },
  { id: 'ctw-13', title: 'Refresh Rate Flex', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Tech', role: 'Console Gamer', desc: 'Aggressively explain why playing at 240Hz is vastly superior to 60fps.' },
  { id: 'ctw-14', title: 'Untangling Cables', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Tech', role: 'Impatient Musician', desc: 'Try to untangle a massive ball of XLR and HDMI cables while a gig is about to start.' },
  { id: 'ctw-15', title: 'Forgot to Save', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Work', role: 'Group Project Partner', desc: 'Confess that you worked for 6 hours but the software crashed before you saved anything.' }
];