import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packMikeThreeScenarios: ScenarioType[] = [
  { id: 'mt3-01', title: 'Makina High Tempo', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Music', role: 'Confused DJ', desc: 'Defend your decision to push a chaotic Makina track all the way up to 180 BPM.' },
  { id: 'mt3-02', title: 'Phonk Cowbell Tuning', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Music', role: 'Audio Engineer', desc: 'Argue that the iconic cowbell melody is slightly out of key with the sub-bass.' },
  { id: 'mt3-03', title: 'Soundtrap Automation Lag', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Tech', role: 'Fellow Producer', desc: 'Complain that adjusting the volume automation curve in the browser is lagging by a full second.' },
  { id: 'mt3-04', title: 'DaVinci Resolve Media Offline', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Tech', role: 'Panicked Editor', desc: 'Stare in horror at a timeline full of giant red "Media Offline" graphics right before a deadline.' },
  { id: 'mt3-05', title: 'CapCut Timeline Snap', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Tech', role: 'Content Creator', desc: 'Yell at the software because the audio clip refuses to snap to the exact video frame.' },
  { id: 'mt3-06', title: 'HandBrake Artifacting', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Tech', role: 'Client', desc: 'Explain why the highly compressed video export is full of blocky pixel artifacts during fast motion.' },
  { id: 'mt3-07', title: 'Adobe Audition Clipping', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Tech', role: 'Voice Actor', desc: 'Tell a voice actor they need to re-record because they screamed directly into the mic and clipped the audio.' },
  { id: 'mt3-08', title: 'John Hizaki Alias Confusion', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Music', role: 'Event Promoter', desc: 'Explain why your developer alias is Ajxrhaider but your artist profile is John Hizaki.' },
  { id: 'mt3-09', title: 'Missing 808 Sample', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Music', role: 'Co-Producer', desc: 'Panic because you accidentally deleted the core 808 bass sample from the project directory.' },
  { id: 'mt3-10', title: 'Blown Studio Monitor', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Music', role: 'Studio Manager', desc: 'Apologize for accidentally blowing out the left studio monitor with an uncompressed bass drop.' },
  { id: 'mt3-11', title: 'XLR Cable Static', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Tech', role: 'Sound Tech', desc: 'Troubleshoot a relentless buzzing noise that is ruining your microphone recording.' },
  { id: 'mt3-12', title: 'Copyright Strike False Positive', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Work', role: 'YouTube Support', desc: 'Appeal an automated copyright strike on a track you generated completely from scratch.' },
  { id: 'mt3-13', title: 'Exporting in WAV vs MP3', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Music', role: 'Clueless Client', desc: 'Explain why they absolutely need the 50MB WAV file for a professional master instead of a tiny MP3.' },
  { id: 'mt3-14', title: 'Vocoder Intelligibility', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Music', role: 'Vocalist', desc: 'Argue that applying maximum vocoder distortion makes the lyrics completely impossible to understand.' },
  { id: 'mt3-15', title: 'Bitcrusher Overused', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Music', role: 'Harsh Critic', desc: 'Defend your artistic choice to put a heavy bitcrusher effect on the master output channel.' }
];