import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packLimaTwoScenarios: ScenarioType[] = [
  { id: 'ltw-01', title: 'Voix Talk AI Integration', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Work', role: 'Skeptical Manager', desc: 'Defend your proposal to integrate an AI virtual assistant into the company\'s WordPress Elementor site.' },
  { id: 'ltw-02', title: 'The Stolen Credit', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Work', role: 'Two-Faced Coworker', desc: 'Confront the colleague who just presented your exact network optimization strategy as their own.' },
  { id: 'ltw-03', title: 'NYSC CDS Meeting', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Work', role: 'CDS President', desc: 'Make up a highly elaborate excuse for why you missed the mandatory Community Development Service meeting.' },
  { id: 'ltw-04', title: 'Unpaid Invoice', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Work', role: 'Evasive Client', desc: 'Politely but firmly demand payment for a web design invoice that is 45 days past due.' },
  { id: 'ltw-05', title: 'NOC Internet Down', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Tech', role: 'Panicked ISP Tech', desc: 'Scream at your ISP because the actual Network Operations Center has lost internet access.' },
  { id: 'ltw-06', title: 'The Friday PDF Edit', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Work', role: 'Technologically Illiterate Boss', desc: 'Explain why you cannot just "easily change the text" on a flattened, scanned JPEG of a PDF.' },
  { id: 'ltw-07', title: 'Office Fridge Thief', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Work', role: 'Defensive Colleague', desc: 'Interrogate the person you suspect of eating your clearly labeled Tupperware of Jollof rice.' },
  { id: 'ltw-08', title: 'Team Building Dread', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Work', role: 'Overly Enthusiastic HR', desc: 'Try to opt out of a mandatory corporate "trust fall and improv" retreat.' },
  { id: 'ltw-09', title: 'Resume Gap', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Work', role: 'Hiring Manager', desc: 'Explain that your 6-month employment gap was spent "building a custom 3D game engine in C++."' },
  { id: 'ltw-10', title: 'Toner Cartridge Outage', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Work', role: 'Office Admin', desc: 'Argue that it is not your fault the printer is out of cyan toner when you only print in black and white.' },
  { id: 'ltw-11', title: 'The Awkward Elevator', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Everyday', role: 'Company CEO', desc: 'Survive a 40-floor elevator ride with the CEO without saying anything career-ending.' },
  { id: 'ltw-12', title: 'Salary Renegotiation', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Work', role: 'Tight-Fisted Boss', desc: 'Counter a terrible 2% annual raise offer with a detailed list of your IT deployments.' },
  { id: 'ltw-13', title: 'Last Minute PTO', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Work', role: 'Scheduling Manager', desc: 'Beg for tomorrow off because a highly anticipated video game is launching at midnight.' },
  { id: 'ltw-14', title: 'The Broken Coffee Machine', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Work', role: 'Caffeinated Colleague', desc: 'Try to fix the office espresso machine while three angry coworkers stare at you.' },
  { id: 'ltw-15', title: 'Explaining a Meme', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Work', role: 'Confused Boomer', desc: 'Explain the nuanced irony of a Gen Z meme you accidentally posted in the general Slack channel.' }
];