import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packLimaThreeScenarios: ScenarioType[] = [
  { id: 'lt3-01', title: 'Blood Strike Camper', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Gaming', role: 'Salty Opponent', desc: 'Send an angry message to the sniper who sat in the exact same window for the entire battle royale match.' },
  { id: 'lt3-02', title: 'Sekiro Posture Break', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Gaming', role: 'Twitch Chat', desc: 'Defend yourself after your posture was broken immediately before landing the final deathblow.' },
  { id: 'lt3-03', title: 'ZZZ Battery Drain', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Gaming', role: 'F2P Player', desc: 'Complain that you ran out of battery charges in Zenless Zone Zero and have nothing left to grind.' },
  { id: 'lt3-04', title: 'Warframe Host Migration', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Gaming', role: 'Squadmate', desc: 'Yell at your screen as a host migration kicks you out of the mission and deletes all your loot.' },
  { id: 'lt3-05', title: 'Shadow Fight 3 Event Grind', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Gaming', role: 'Tired Player', desc: 'Rant about having to fight the exact same boss 40 times just to unlock a single piece of armor.' },
  { id: 'lt3-06', title: 'Combat Master Slide Cancel', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Gaming', role: 'Casual Player', desc: 'Argue that breaking your controller to perform a slide-cancel is not a fun gameplay mechanic.' },
  { id: 'lt3-07', title: 'Plague Inc Cure', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Gaming', role: 'Frustrated Pathogen', desc: 'Watch in horror as global scientists cure your highly infectious virus at 99% completion.' },
  { id: 'lt3-08', title: 'Murim Qi Deviation', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Pop Culture', role: 'Sect Doctor', desc: 'Explain that the protagonist only survived coughing up blood because of extreme plot armor.' },
  { id: 'lt3-09', title: 'Absolute Sword Sense Cliffhanger', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Pop Culture', role: 'Webtoon Reader', desc: 'Complain to a friend about a brutal chapter cliffhanger right before a massive martial arts duel.' },
  { id: 'lt3-10', title: 'BlueString Universe Cameo', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Pop Culture', role: 'Lore Theorist', desc: 'Point out a subtle background character cameo that proves Study Group and Hanlim Gym are connected.' },
  { id: 'lt3-11', title: 'Record of Ragnarok Animation', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Pop Culture', role: 'Disappointed Fan', desc: 'Complain that the climax of a highly anticipated fight scene was essentially a PowerPoint presentation.' },
  { id: 'lt3-12', title: 'Chainsaw Man Contract', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Pop Culture', role: 'Devil Hunter', desc: 'Argue that sacrificing your fingernails to summon a weak devil is a terrible trade.' },
  { id: 'lt3-13', title: 'Spy x Family Anya Smug Face', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Pop Culture', role: 'Manga Artist', desc: 'Debate why Anya\'s iconic smug smile is the peak of modern comedy design.' },
  { id: 'lt3-14', title: 'Dragon Ball Power Creep', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Pop Culture', role: 'Old School Fan', desc: 'Complain that blowing up a planet isn\'t even considered an impressive feat anymore.' },
  { id: 'lt3-15', title: 'Gacha Pity Broken', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Gaming', role: 'Whale Player', desc: 'Try to justify spending another $50 just to guarantee you hit the hard pity drop.' }
];