import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packAlphaScenarios: ScenarioType[] = [
  { id: 'alp-01', title: 'The Dropped Phone', originalLanguage: 'Japanese', availableLanguages: ALL_LANGUAGES, category: 'Everyday', role: 'Stranger', desc: 'Tap a stranger on the shoulder to tell them they dropped their phone.' },
  { id: 'alp-02', title: 'Borrowing a Charger', originalLanguage: 'English', availableLanguages: ['English', 'Pidgin English', 'Spanish', 'French'], category: 'Everyday', role: 'Library Patron', desc: 'Ask the person next to you if you can borrow their USB-C charger for 10 minutes.' },
  { id: 'alp-03', title: 'Lost Dog', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English', 'German'], category: 'Everyday', role: 'Local Resident', desc: 'Ask a local if they have seen a golden retriever running down the street.' },
  { id: 'alp-04', title: 'Queue Jumper', originalLanguage: 'German', availableLanguages: ['German', 'English', 'Mandarin'], category: 'Incidents', role: 'Impatient Customer', desc: 'Politely but firmly tell someone they just cut in line at the grocery store.' },
  { id: 'alp-05', title: 'Subway Delay', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English', 'Japanese'], category: 'Travel', role: 'Platform Attendant', desc: 'Ask how long the train delay will be and if there is a replacement bus.' },
  { id: 'alp-06', title: 'Holding the Elevator', originalLanguage: 'French', availableLanguages: ALL_LANGUAGES, category: 'Everyday', role: 'Office Worker', desc: 'Yell for someone to hold the elevator, then thank them and make small talk.' },
  { id: 'alp-07', title: 'Wrong Number', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English', 'Spanish'], category: 'Everyday', role: 'Confused Caller', desc: 'Explain to an angry caller that they have dialed the wrong number.' },
  { id: 'alp-08', title: 'Taking a Photo', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English', 'French', 'Arabic'], category: 'Travel', role: 'Tourist', desc: 'Ask a passerby to take a full-body photo of you in front of a monument.' },
  { id: 'alp-09', title: 'Dead Battery', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Incidents', role: 'Mechanic', desc: 'Explain that your car battery is dead and ask for a jump start.' },
  { id: 'alp-10', title: 'Rainy Umbrella', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English', 'German'], category: 'Everyday', role: 'Cafe Patron', desc: 'Apologize for dripping your wet umbrella on someone\'s shoes.' },
  { id: 'alp-11', title: 'Missed Stop', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English', 'Russian'], category: 'Travel', role: 'Bus Driver', desc: 'Frantically ask the driver to let you off because you missed your stop.' },
  { id: 'alp-12', title: 'Gym Spotter', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Everyday', role: 'Bodybuilder', desc: 'Ask a massive guy at the gym if he can spot your bench press.' },
  { id: 'alp-13', title: 'Late Return', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Everyday', role: 'Librarian', desc: 'Apologize for returning a book three weeks late and ask about the fine.' },
  { id: 'alp-14', title: 'Buying Stamps', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'Portuguese', 'English'], category: 'Everyday', role: 'Post Office Clerk', desc: 'Buy international stamps to send three postcards to North America.' },
  { id: 'alp-15', title: 'Wifi Password', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English', 'Hindi'], category: 'Everyday', role: 'Cafe Waiter', desc: 'Order an espresso and ask for the Wi-Fi password.' },
  { id: 'alp-16', title: 'Seat Taken?', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English', 'Pidgin English'], category: 'Everyday', role: 'Commuter', desc: 'Ask if the empty seat next to someone on the train is taken.' },
  { id: 'alp-17', title: 'Lost Keys', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Incidents', role: 'Roommate', desc: 'Ask your roommate if they have seen your car keys anywhere in the house.' },
  { id: 'alp-18', title: 'Petting a Dog', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Everyday', role: 'Dog Owner', desc: 'Ask a stranger if it is okay to pet their very cute Shiba Inu.' },
  { id: 'alp-19', title: 'Spilled Drink', originalLanguage: 'French', availableLanguages: ['French', 'English', 'Italian'], category: 'Incidents', role: 'Customer', desc: 'Profusely apologize for accidentally knocking over someone\'s coffee.' },
  { id: 'alp-20', title: 'Concert Tickets', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Everyday', role: 'Box Office', desc: 'Ask if there are any last-minute standing tickets available for tonight\'s show.' },
  { id: 'alp-21', title: 'Luggage Weight', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Travel', role: 'Check-in Agent', desc: 'Plead with the agent to ignore the 2kg of extra weight in your suitcase.' },
  { id: 'alp-22', title: 'Finding the Restroom', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Everyday', role: 'Mall Janitor', desc: 'Ask for directions to the nearest public restroom.' },
  { id: 'alp-23', title: 'Broken ATM', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English', 'Spanish'], category: 'Incidents', role: 'Bank Teller', desc: 'Report that the ATM outside just swallowed your debit card.' },
  { id: 'alp-24', title: 'Lending a Pen', originalLanguage: 'Italian', availableLanguages: ALL_LANGUAGES, category: 'Everyday', role: 'Student', desc: 'Ask the person sitting next to you in class if you can borrow a pen.' },
  { id: 'alp-25', title: 'Stuck in Traffic', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Work', role: 'Your Boss', desc: 'Call your boss to explain you will be 30 minutes late due to a massive gridlock.' }
];