import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packPapaThreeScenarios: ScenarioType[] = [
  { id: 'pt3-01', title: 'Submarine Leak', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Incidents', role: 'Submarine Captain', desc: 'Frantically report that the screen door someone installed on the submarine is leaking.' },
  { id: 'pt3-02', title: 'Kraken Attack Insurance', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Work', role: 'Insurance Adjuster', desc: 'Try to file a maritime insurance claim for a ship pulled under by giant tentacles.' },
  { id: 'pt3-03', title: 'Scuba Hand Signals', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Incidents', role: 'Dive Master', desc: 'Try to explain through frantic underwater gestures that a shark stole your flipper.' },
  { id: 'pt3-04', title: 'Megalodon Spotting', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Everyday', role: 'Skeptical Marine Biologist', desc: 'Argue that the 60-foot shadow you saw on the sonar was definitely not a glitch.' },
  { id: 'pt3-05', title: 'Bermuda Triangle GPS', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Travel', role: 'Ship Navigator', desc: 'Yell at the navigator because Apple Maps just told you to turn left into a whirlpool.' },
  { id: 'pt3-06', title: 'Merfolk Negotiation', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Funny', role: 'Mermaid Queen', desc: 'Negotiate a peace treaty after your anchor accidentally dropped on their coral palace.' },
  { id: 'pt3-07', title: 'Marianas Trench Wi-Fi', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Tech', role: 'Submersible Pilot', desc: 'Complain that the Wi-Fi is terribly slow while you are 35,000 feet underwater.' },
  { id: 'pt3-08', title: 'Ghost Ship Boarding', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Funny', role: 'Ghost Pirate Captain', desc: 'Critique the cleanliness of the cursed ghost ship you just accidentally boarded.' },
  { id: 'pt3-09', title: 'Whale Song Translation', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Work', role: 'Lead Researcher', desc: 'Explain that the majestic whale song you recorded actually translates to a Yo Mama joke.' },
  { id: 'pt3-10', title: 'Icebreaker Ship Jam', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Work', role: 'Chief Engineer', desc: 'Explain how the nuclear icebreaker got stuck in a perfectly square ice cube.' },
  { id: 'pt3-11', title: 'Lighthouse Isolation', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Work', role: 'Relief Worker', desc: 'Beg the relief boat not to leave after you spent 6 months alone in a lighthouse.' },
  { id: 'pt3-12', title: 'Oil Rig Storm', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Incidents', role: 'Rig Manager', desc: 'Demand an evacuation flight while a Category 5 hurricane approaches the oil rig.' },
  { id: 'pt3-13', title: 'Pearl Diving Cramp', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Incidents', role: 'Boat Captain', desc: 'Gasp for air and explain that you dropped the giant pearl because your calf cramped.' },
  { id: 'pt3-14', title: 'Naval Sonar Operator', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Work', role: 'Fleet Admiral', desc: 'Explain that the hostile submarine ping is actually just a school of very loud shrimp.' },
  { id: 'pt3-15', title: 'Sea Sickness', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Travel', role: 'Cruise Director', desc: 'Demand that they stop the massive cruise ship immediately because you are dizzy.' }
];