import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packIndiaTwoScenarios: ScenarioType[] = [
  { id: 'itw-01', title: 'Lost on the Metro', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English', 'Korean'], category: 'Travel', role: 'Commuter', desc: 'Ask a Tokyo commuter if this train is actually going to Akihabara or if you are on the wrong line entirely.' },
  { id: 'itw-02', title: 'Rental Bike Flat Tire', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English', 'German'], category: 'Travel', role: 'Bike Shop Owner', desc: 'Refuse to pay the damage fee for a rental bike that got a flat tire 5 minutes after you left.' },
  { id: 'itw-03', title: 'Turbulence Panic', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Travel', role: 'Nervous Passenger', desc: 'Reassure the terrified passenger next to you that the plane is not going to fall out of the sky.' },
  { id: 'itw-04', title: 'Hostel Snoring', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Travel', role: 'Offended Backpacker', desc: 'Confront a guy in your 12-bed hostel dorm who sounds like a chainsaw when he sleeps.' },
  { id: 'itw-05', title: 'Rideshare Vomit', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Travel', role: 'Uber Driver', desc: 'Beg the driver not to charge you the $150 cleaning fee because it was your friend, not you.' },
  { id: 'itw-06', title: 'Canceled Flight Hotel', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Travel', role: 'Airline Rep', desc: 'Demand a hotel voucher that isn\'t for a one-star motel next to a highway.' },
  { id: 'itw-07', title: 'Missing Passport Stamp', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Travel', role: 'Border Guard', desc: 'Explain why your passport has an entry stamp but no exit stamp from your last destination.' },
  { id: 'itw-08', title: 'Train Toilet Broken', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Travel', role: 'Conductor', desc: 'Desperately ask how long until the next station because the on-board restroom is out of order.' },
  { id: 'itw-09', title: 'Toll Booth No Cash', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Travel', role: 'Toll Operator', desc: 'Explain that the card reader is broken and you have absolutely zero cash on you.' },
  { id: 'itw-10', title: 'Camping Tent Collapse', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Travel', role: 'Smug Fellow Camper', desc: 'Ask to borrow some duct tape after a windstorm completely destroys your cheap tent.' },
  { id: 'itw-11', title: 'Rented Scooter Crash', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Travel', role: 'Rental Vendor', desc: 'Try to play off the massive scratch on the side of the electric scooter you just returned.' },
  { id: 'itw-12', title: 'Delayed Luggage Compensation', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Travel', role: 'Baggage Claim Agent', desc: 'Argue that $50 is not enough to replace your entire wardrobe for a 4-day business trip.' },
  { id: 'Pop-13', title: 'Stolen Towel at the Beach', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Travel', role: 'Suspicious Tourist', desc: 'Accuse the person next to you of stealing your highly specific, brightly colored beach towel.' },
  { id: 'itw-14', title: 'Skipping the Security Line', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Travel', role: 'Angry Traveler', desc: 'Beg the people in front of you to let you pass because your gate closes in 5 minutes.' },
  { id: 'itw-15', title: 'Wrong Cruise Ship', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Travel', role: 'Security Officer', desc: 'Explain how you somehow walked onto the wrong massive cruise ship after a port excursion.' }
];