import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packOscarScenarios: ScenarioType[] = [
  { id: 'osc-01', title: 'The Hydration Error', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Tech', role: 'Senior React Dev', desc: 'Try to explain why your Next.js app is throwing a massive hydration mismatch error in production.' },
  { id: 'osc-02', title: 'Accidental Drop Table', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English', 'German'], category: 'Work', role: 'Furious DBA', desc: 'Beg for forgiveness after accidentally dropping the primary production database.' },
  { id: 'osc-03', title: 'Ransomware Negotiation', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Tech', role: 'Hacker Syndicate', desc: 'Negotiate the Bitcoin ransom to unlock your company\'s encrypted mainframes.' },
  { id: 'osc-04', title: 'Vercel Bill Shock', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Work', role: 'Finance Director', desc: 'Explain why the monthly Vercel hosting bill suddenly spiked to $4,000 due to a rogue API loop.' },
  { id: 'osc-05', title: 'Stolen AWS Keys', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English', 'Portuguese'], category: 'Tech', role: 'AWS Support Agent', desc: 'Frantically request a server shutdown because you hardcoded your AWS keys into a public GitHub repo.' },
  { id: 'osc-06', title: 'The Endless Boot Loop', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Tech', role: 'Lenovo Support', desc: 'Complain that a firmware update threw your laptop into an inescapable boot loop.' },
  { id: 'osc-07', title: 'Expired SSL Certificate', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Work', role: 'Angry Client', desc: 'Calm down a client whose e-commerce site is showing a massive security warning because you forgot to renew the SSL.' },
  { id: 'osc-08', title: 'Bypassing the Firewall', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Tech', role: 'Strict Sysadmin', desc: 'Try to convince your sysadmin to open port 25565 so you can host a "stress-test server."' },
  { id: 'osc-09', title: 'The Ghost in the Code', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Tech', role: 'Superstitious Programmer', desc: 'Argue that the legacy C++ codebase is actually haunted and refuses to compile on Tuesdays.' },
  { id: 'osc-10', title: 'Linux Supremacy', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Tech', role: 'Windows Fanboy', desc: 'Aggressively debate why compiling your own kernel on Ubuntu is better than using Windows 11.' },
  { id: 'osc-11', title: 'SQL Injection Panic', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Tech', role: 'Security Auditor', desc: 'Explain how a user named "Robert\'); DROP TABLE Students;--" destroyed your backend.' },
  { id: 'osc-12', title: 'Corrupted Backup', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Tech', role: 'IT Manager', desc: 'Admit that the NAS backup drive has been silently failing for the past six months.' },
  { id: 'osc-13', title: 'Spilled Coffee on Server', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Incidents', role: 'Datacenter Tech', desc: 'Explain how a full cup of coffee ended up inside the primary blade server.' },
  { id: 'osc-14', title: 'Missing Semicolon', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Work', role: 'Exhausted Teammate', desc: 'Apologize for breaking the build because you missed a single semicolon on line 4,092.' },
  { id: 'osc-15', title: 'Unplugged Router', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Incidents', role: 'Confused Janitor', desc: 'Ask the cleaning staff why they unplugged the core office router to plug in a vacuum cleaner.' }
];