import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packDeltaThreeScenarios: ScenarioType[] = [
  { id: 'dt3-01', title: 'The Sudo Incident', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Tech', role: 'Angry Sysadmin', desc: 'Beg for forgiveness after accidentally revoking your own sudo privileges on a production server.' },
  { id: 'dt3-02', title: 'Arch Linux Flex', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Tech', role: 'Arch User', desc: 'Defend Ubuntu 26 LTS against an Arch Linux user who insists you should build everything from source.' },
  { id: 'dt3-03', title: 'Missing Semi-Colon', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Tech', role: 'Exhausted Colleague', desc: 'Apologize for a missing semi-colon that took down the entire staging environment for six hours.' },
  { id: 'dt3-04', title: 'GitHub Outage', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Tech', role: 'Panicked PM', desc: 'Explain that you literally cannot deploy the hotfix because GitHub is currently down globally.' },
  { id: 'dt3-05', title: 'Docker Image Size', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Tech', role: 'Cloud DevOps', desc: 'Argue why your simple "Hello World" app requires a 4GB Docker image.' },
  { id: 'dt3-06', title: 'NPM Install Hang', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Tech', role: 'Impatient Client', desc: 'Stall the client on a Zoom call while `npm install` takes 20 minutes to resolve dependencies.' },
  { id: 'dt3-07', title: 'Forgot to Save', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Tech', role: 'Sympathetic Friend', desc: 'Rant about how your code editor crashed before you could save a 500-line Python script.' },
  { id: 'dt3-08', title: 'The Regex Wall', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Tech', role: 'Code Reviewer', desc: 'Try to explain exactly what a massive, terrifying block of Regex is actually doing.' },
  { id: 'dt3-09', title: 'API Key Leak', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Tech', role: 'Security Team', desc: 'Explain how you accidentally pushed the main database credentials to a public GitHub repo.' },
  { id: 'dt3-10', title: 'CSS Centering', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Tech', role: 'Junior Dev', desc: 'Try to help a junior developer horizontally and vertically center a div without using Flexbox.' },
  { id: 'dt3-11', title: 'Expired SSL', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Work', role: 'Furious CEO', desc: 'Explain why the company homepage is displaying a massive red security warning to all users.' },
  { id: 'dt3-12', title: 'The Unplugged Server', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Incidents', role: 'Confused Janitor', desc: 'Find out why the janitor unplugged the main database server to plug in a floor buffer.' },
  { id: 'dt3-13', title: 'Out of Memory', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Tech', role: 'Hosting Support', desc: 'Argue that your code doesn\'t have a memory leak, the server just needs more RAM.' },
  { id: 'dt3-14', title: 'Spaghetti Code', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Tech', role: 'New Hire', desc: 'Try to explain the complex, undocumented architecture of an ancient legacy app.' },
  { id: 'dt3-15', title: 'Ignoring Warnings', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Tech', role: 'Compiler', desc: 'Argue with a compiler that throws 400 deprecation warnings but still technically builds.' }
];