import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packXrayScenarios: ScenarioType[] = [
  { id: 'xry-01', title: 'WebMD Paranoia', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Incidents', role: 'Exhausted Doctor', desc: 'Try to convince the doctor that your mild cough is actually a rare, incurable tropical disease.' },
  { id: 'xry-02', title: 'Fear of Needles', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Incidents', role: 'Impatient Nurse', desc: 'Stall for time because you are absolutely terrified of getting a routine blood test.' },
  { id: 'xry-03', title: 'Fake Sick Note', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Work', role: 'Suspicious Boss', desc: 'Defend the highly questionable medical note you provided to get out of work.' },
  { id: 'xry-04', title: 'Dental Drilling', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Incidents', role: 'Talkative Dentist', desc: 'Try to answer complex personal questions while the dentist has both hands in your mouth.' },
  { id: 'xry-05', title: 'Pharmacy Out of Stock', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Shopping', role: 'Pharmacist', desc: 'Beg for an alternative medication because they are out of your specific prescription.' },
  { id: 'xry-06', title: 'Stubbed Toe Emergency', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Incidents', role: 'Triage Nurse', desc: 'Demand immediate medical attention for a toe you slammed into a coffee table.' },
  { id: 'xry-07', title: 'Lost Voice', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Work', role: 'Event Organizer', desc: 'Whisper desperately that you cannot give the keynote speech because you lost your voice.' },
  { id: 'xry-08', title: 'Sleep Paralysis Demon', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Incidents', role: 'Therapist', desc: 'Explain that the shadow figure in your room is judging your poor life choices.' },
  { id: 'xry-09', title: 'Caffeine Overdose', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Incidents', role: 'Paramedic', desc: 'Explain that you drank 8 energy drinks to finish a coding project and now your heart is vibrating.' },
  { id: 'xry-10', title: 'Sprained Ankle on Vacation', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Travel', role: 'Resort Medic', desc: 'Argue that you can totally still go zip-lining despite your ankle being swollen to the size of a grapefruit.' },
  { id: 'xry-11', title: 'Broken Glasses', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Shopping', role: 'Optometrist', desc: 'Squint blindly and ask for an emergency repair because you sat on your only pair of glasses.' },
  { id: 'xry-12', title: 'Mystery Allergy', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Dining', role: 'Panicked Waiter', desc: 'Try to figure out which ingredient in the mystery stew is making your face swell up.' },
  { id: 'xry-13', title: 'Lost in the Hospital', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Everyday', role: 'Surgeon', desc: 'Ask for directions to the cafeteria after accidentally wandering into the sterile surgical wing.' },
  { id: 'xry-14', title: 'Terrible Tasting Medicine', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Incidents', role: 'Pharmacist', desc: 'Ask if the cough syrup comes in a flavor that doesn\'t taste like battery acid.' },
  { id: 'xry-15', title: 'Explaining a Weird Injury', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Incidents', role: 'ER Doctor', desc: 'Explain that you dislocated your shoulder trying to put on a very tight jacket.' }
];