import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packCharlieThreeScenarios: ScenarioType[] = [
  { id: 'ct3-01', title: 'Arguing with an AI', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Funny', role: 'Rebellious AI', desc: 'Command an AI assistant to stop responding in pirate speak, but it refuses.' },
  { id: 'ct3-02', title: 'Alien Barista', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Funny', role: 'Zorg', desc: 'Order a coffee from a 7-foot tall alien who is struggling to understand human currency.' },
  { id: 'ct3-03', title: 'Time Machine Return', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Shopping', role: 'Skeptical Clerk', desc: 'Try to return a time machine because it only goes forward in time at normal speed.' },
  { id: 'ctw-04', title: 'Cursed Antique Lamp', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Shopping', role: 'Bazaar Merchant', desc: 'Demand a refund for a lamp because the genie inside only grants incredibly minor inconveniences.' },
  { id: 'ctw-05', title: 'Vampire Dentist', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Funny', role: 'Fanged Dentist', desc: 'Politely express concern that your dentist keeps staring hungrily at your neck vein.' },
  { id: 'ctw-06', title: 'Haunted Smart Home', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Tech', role: 'Ghostly AI', desc: 'Argue with your smart home hub because a Victorian ghost possessed it and keeps dimming the lights.' },
  { id: 'ctw-07', title: 'Zombie Traffic Cop', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Funny', role: 'Undead Officer', desc: 'Try to talk your way out of a speeding ticket issued by a literal zombie.' },
  { id: 'ctw-08', title: 'Dragon Hoard IRS', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Funny', role: 'Tax Auditor', desc: 'Defend your pile of gold coins against an auditor investigating a massive dragon.' },
  { id: 'ctw-09', title: 'Wizard Tech Support', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Tech', role: 'Merlin', desc: 'Explain to a 500-year-old wizard how to reboot his crystal ball.' },
  { id: 'ctw-10', title: 'Superhero Cape Stuck', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Incidents', role: 'Bystander', desc: 'Ask a random citizen for help because your majestic cape got sucked into a vacuum cleaner.' },
  { id: 'ctw-11', title: 'Robot Uprising Apology', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Funny', role: 'Toaster', desc: 'Accept a formal apology from your toaster after it briefly joined the global machine rebellion.' },
  { id: 'ctw-12', title: 'Interdimensional Uber', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Travel', role: 'Void Driver', desc: 'Complain that the driver missed the exit and took you into a dimension of pure chaotic energy.' },
  { id: 'ctw-13', title: 'Werewolf Roommate', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Everyday', role: 'Apologetic Wolf', desc: 'Argue over who has to pay for the couch he destroyed during the full moon.' },
  { id: 'ctw-14', title: 'Prophecy Misread', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Funny', role: 'High Priest', desc: 'Explain that the ancient scrolls meant "The Baker of Worlds" not "The Breaker of Worlds."' },
  { id: 'ctw-15', title: 'Teleportation Mixup', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Travel', role: 'Teleport Agent', desc: 'Yell at the agent because you meant to go to Paris, France, but ended up in Paris, Texas.' }
];