import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packDeltaScenarios: ScenarioType[] = [
  // OFFICE & PROFESSIONAL CHAOS
  { id: 'dlt-01', title: 'Game Release Day Off', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Work', role: 'Strict Manager', desc: 'Try to convince your boss you need Friday off for "personal reasons" when a major game drops.' },
  { id: 'dlt-02', title: 'The Reply-All Disaster', originalLanguage: 'French', availableLanguages: ['French', 'English', 'Spanish'], category: 'Work', role: 'HR Director', desc: 'Apologize for accidentally sending a very personal meme to the entire company mailing list.' },
  { id: 'dlt-03', title: 'Over-Budget Expenses', originalLanguage: 'German', availableLanguages: ['German', 'English', 'Dutch'], category: 'Work', role: 'Finance Officer', desc: 'Defend a wildly expensive corporate dinner on your latest expense report.' },
  { id: 'dlt-04', title: 'Sleeping in the Meeting', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English', 'Korean'], category: 'Work', role: 'Department Head', desc: 'Explain that you were "deep in thought" and definitely not snoring during the presentation.' },
  { id: 'dlt-05', title: 'Freelance Negotiation', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Work', role: 'Client', desc: 'Negotiate a better rate for building a custom ERP web app.' },
  { id: 'dlt-06', title: 'Unblock this Website', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English', 'Turkish'], category: 'Tech', role: 'Stubborn Sysadmin', desc: 'Beg IT to unblock a specific forum claiming it is vital for your "software research."' },
  { id: 'dlt-07', title: 'Terrible Movie Pitch', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English', 'French'], category: 'Work', role: 'Studio Executive', desc: 'Pitch a movie idea so horribly absurd they might actually buy it.' },
  { id: 'dlt-08', title: 'VIP Club Entry', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English', 'Portuguese'], category: 'Everyday', role: 'Bouncer', desc: 'Try to talk your way past the velvet rope without being on the guest list.' },
  
  // DOMESTIC & STREET LEVEL
  { id: 'dlt-09', title: 'The Neighbor\'s Tree', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Everyday', role: 'Defensive Neighbor', desc: 'Complain that their massive tree is dropping leaves all over your pristine driveway.' },
  { id: 'dlt-10', title: 'Torn Suit Repair', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English', 'Turkish'], category: 'Shopping', role: 'Tailor', desc: 'Explain how you ripped the pants dancing and ask if it can be fixed by tomorrow.' },
  { id: 'dlt-11', title: 'Expired Milk', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English', 'German'], category: 'Shopping', role: 'Supermarket Manager', desc: 'Demand a refund for milk you just realized expired three days ago.' },
  { id: 'dlt-12', title: 'Lost Coat Check', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English', 'Japanese'], category: 'Incidents', role: 'Coat Check Attendant', desc: 'Try to get your jacket back after completely losing your ticket number.' },
  { id: 'dlt-13', title: 'Jaywalking Ticket', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Incidents', role: 'Traffic Cop', desc: 'Try to talk your way out of a fine for crossing the street outside the crosswalk.' },
  { id: 'dlt-14', title: 'Lottery Winner Plans', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Everyday', role: 'Curious Cashier', desc: 'Buy a lottery ticket and confidently explain exactly how you will spend the millions.' },
  { id: 'dlt-15', title: 'Terrible Stomach Ache', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English', 'Spanish'], category: 'Shopping', role: 'Pharmacist', desc: 'Desperately ask for the strongest over-the-counter medicine for food poisoning.' },
  { id: 'dlt-16', title: 'Skipping the Toll', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Incidents', role: 'Toll Gate Operator', desc: 'Argue that your POS transfer went through even though they did not get the alert.' },
  { id: 'dlt-17', title: 'Cold Shower Complaint', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Travel', role: 'Hostel Owner', desc: 'Complain that the water in the shared bathroom is freezing cold.' },
  { id: 'dlt-18', title: 'Buying Weird Souvenirs', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English', 'Arabic'], category: 'Shopping', role: 'Gift Shop Owner', desc: 'Haggle for a terrifyingly ugly ceramic statue you want as a gag gift.' },
  { id: 'dlt-19', title: 'Dog in the Park', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Everyday', role: 'Park Ranger', desc: 'Pretend you did not see the "No Dogs Allowed" sign while walking your pet.' },
  { id: 'dlt-20', title: 'Spoiled Kid on Train', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Travel', role: 'Defensive Parent', desc: 'Politely ask a parent to stop their child from kicking the back of your seat.' },
  { id: 'dlt-21', title: 'Ruined Laundry', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Shopping', role: 'Dry Cleaner', desc: 'Yell at the dry cleaner for shrinking your favorite wool sweater.' },
  { id: 'dlt-22', title: 'Movie Spoiler Threat', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Everyday', role: 'Chatty Friend', desc: 'Warn your friend that if they spoil the ending of the movie, you will walk out.' },
  { id: 'dlt-23', title: 'Incorrect Change', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Shopping', role: 'Convenience Store Clerk', desc: 'Point out that they shorted you by exactly 50 cents.' },
  { id: 'dlt-24', title: 'Asking for Ketchup', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English', 'Italian'], category: 'Dining', role: 'Offended Chef', desc: 'Ask for ketchup at a highly-rated traditional restaurant.' },
  { id: 'dlt-25', title: 'Evading Small Talk', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Everyday', role: 'Overly Friendly Neighbor', desc: 'Desperately try to end a conversation with a neighbor so you can go inside.' }
];