import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packKiloThreeScenarios: ScenarioType[] = [
  { id: 'kt3-01', title: 'POS Network Failure', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Shopping', role: 'Angry Vendor', desc: 'Stand in an awkward silence after the POS machine says "Issuer Inoperative" for the third time.' },
  { id: 'kt3-02', title: 'NYSC PPA Rejection', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Work', role: 'School Principal', desc: 'Beg the principal to formally reject you so you can find a tech role instead of teaching.' },
  { id: 'kt3-03', title: 'Danfo Change Wahala', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Travel', role: 'Bus Conductor', desc: 'Refuse to step off the bus into the dust until the conductor produces your exact 100 Naira change.' },
  { id: 'kt3-04', title: 'Nepa Low Voltage', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Everyday', role: 'Neighbor', desc: 'Complain that Nepa brought the light, but the voltage is so low the fan is barely spinning.' },
  { id: 'kt3-05', title: 'Ado FCT Dust', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Everyday', role: 'Dry Cleaner', desc: 'Complain that your white shirt turned completely brown after a single Keke ride through Ado.' },
  { id: 'kt3-06', title: 'Jerrycan Fuel Hustle', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Incidents', role: 'Fuel Attendant', desc: 'Beg the attendant to fill your 25-liter jerrycan because they are only selling to cars.' },
  { id: 'kt3-07', title: 'Omo-Onile Harassment', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Incidents', role: 'Street Thug', desc: 'Refuse to pay an illegal "foundation fee" just to offload building materials from a truck.' },
  { id: 'kt3-08', title: 'Shawarma Without Sausage', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Dining', role: 'Shawarma Vendor', desc: 'Demand a refund after biting into a 3,000 Naira shawarma that contains absolutely zero sausages.' },
  { id: 'kt3-09', title: 'Fake Customer Care', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Tech', role: 'Scammer', desc: 'Play along and waste the time of a scammer claiming your bank account has been blocked.' },
  { id: 'kt3-10', title: 'Keke Napep Overtaking', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Travel', role: 'Terrified Passenger', desc: 'Beg your Keke driver to stop trying to race a massive articulated trailer on the highway.' },
  { id: 'kt3-11', title: 'Washed Away Road', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Travel', role: 'Taxi Driver', desc: 'Argue about the fare after the driver refuses to cross a massive pothole flooded by the rain.' },
  { id: 'kt3-12', title: 'Generator Spark Plug', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Everyday', role: 'Mechanic', desc: 'Watch your mechanic aggressively clean a spark plug with a wire brush for the fifth time today.' },
  { id: 'kt3-13', title: 'Checkpoint Bribe', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Incidents', role: 'Corrupt Officer', desc: 'Politely refuse to "drop something for the boys" because all your vehicle particulars are intact.' },
  { id: 'kt3-14', title: 'Suya Pepper Too Much', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Dining', role: 'Suya Mallam', desc: 'Gasp for water and complain that the Yaji pepper on the meat is physically burning your throat.' },
  { id: 'kt3-15', title: 'CAC Name Denial', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Work', role: 'Business Partner', desc: 'Rant about how the Corporate Affairs Commission rejected your business name for being "too similar" to another.' }
];