import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packOscarTwoScenarios: ScenarioType[] = [
  { id: 'otw-02', title: 'Japan Flight Booked', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Travel', role: 'Jealous Friend', desc: 'Defend your incredibly complex itinerary for an upcoming 3-week trip to Japan.' },
  { id: 'otw-03', title: 'eSIM Failure in Akihabara', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Tech', role: 'Mobile Clerk', desc: 'Frantically explain that your physical eSIM adapter is not registering the digital profile.' },
  { id: 'otw-04', title: 'Lost Luggage in Transit', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Incidents', role: 'Airline Rep', desc: 'Demand to know how your suitcase ended up in Paris when you flew directly to Berlin.' },
  { id: 'otw-05', title: 'Customs Interrogation', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Incidents', role: 'Border Guard', desc: 'Explain why your passport photo looks absolutely nothing like you do right now.' },
  { id: 'otw-06', title: 'Hotel Double Booked', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Travel', role: 'Night Manager', desc: 'Argue for a free upgrade to the presidential suite because they gave your room to someone else.' },
  { id: 'otw-07', title: 'Catfish Airbnb', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Travel', role: 'Airbnb Host', desc: 'Complain that the "luxury ocean view" is actually a poster of the beach taped to a brick wall.' },
  { id: 'otw-08', title: 'Train Missed by Seconds', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Travel', role: 'Station Guard', desc: 'Beg the guard to open the doors of the high-speed train that is still sitting at the platform.' },
  { id: 'otw-09', title: 'The Long Route Taxi', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Travel', role: 'Shady Taxi Driver', desc: 'Point at your GPS to prove the driver is taking you in circles to run up the meter.' },
  { id: 'otw-10', title: 'Food Poisoning', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Incidents', role: 'Pharmacist', desc: 'Beg for the strongest stomach medication available after eating questionable street food.' },
  { id: 'otw-11', title: 'Tourist Trap Scam', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Incidents', role: 'Aggressive Vendor', desc: 'Refuse to pay $40 for a cheap bracelet they forcefully tied around your wrist.' },
  { id: 'otw-12', title: 'Lost Passport Panic', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Incidents', role: 'Embassy Clerk', desc: 'Explain that your passport fell out of your pocket while riding a rollercoaster.' },
  { id: 'otw-13', title: 'Translating the Menu', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Dining', role: 'Impatient Waiter', desc: 'Struggle to use Google Translate on a menu while the waiter sighs heavily.' },
  { id: 'otw-14', title: 'Buying a Train Ticket', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Travel', role: 'Ticket Agent', desc: 'Try to buy a sleeper ticket for a train that has been sold out for three weeks.' },
  { id: 'otw-15', title: 'Missed Connection', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Travel', role: 'Customer Service', desc: 'Demand a direct flight home after the airline delayed your first leg by 7 hours.' }
];