import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packWhiskeyScenarios: ScenarioType[] = [
  { id: 'wsk-01', title: 'The Stolen Lunch', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Work', role: 'Guilty Coworker', desc: 'Confront the coworker you caught red-handed eating your labeled turkey sandwich.' },
  { id: 'wsk-02', title: 'Friday 4:59 PM Meeting', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Work', role: 'Micromanaging Boss', desc: 'Try to escape a mandatory "quick sync" meeting scheduled one minute before the weekend.' },
  { id: 'wsk-03', title: 'Air Conditioning Wars', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Work', role: 'Freezing Colleague', desc: 'Argue over the office thermostat being set to arctic temperatures.' },
  { id: 'wsk-04', title: 'Buzzword Bingo', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Work', role: 'Startup CEO', desc: 'Try to understand a project brief that consists entirely of meaningless corporate buzzwords.' },
  { id: 'wsk-05', title: 'Lost Security Badge', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Work', role: 'Unsympathetic Guard', desc: 'Beg the lobby security guard to let you into the building for a massive presentation.' },
  { id: 'wsk-06', title: 'Fire Drill Panic', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Incidents', role: 'Fire Warden', desc: 'Explain why you tried to bring your dual monitors down 14 flights of stairs during a drill.' },
  { id: 'wsk-07', title: 'Coffee Machine Sabotage', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Work', role: 'Office Gossip', desc: 'Defend yourself against accusations that you broke the expensive espresso machine.' },
  { id: 'wsk-08', title: 'Casual Friday Disaster', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Work', role: 'HR Manager', desc: 'Explain why you thought a full inflatable T-Rex costume was appropriate for Casual Friday.' },
  { id: 'wsk-09', title: 'IT Ticket Ignored', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Tech', role: 'Lazy Sysadmin', desc: 'Demand to know why your critical IT helpdesk ticket has been open for 3 weeks.' },
  { id: 'wsk-10', title: 'Elevator Silence', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Everyday', role: 'Awkward CEO', desc: 'Try to make normal small talk while trapped in a broken elevator with the company owner.' },
  { id: 'wsk-11', title: 'Expense Report Rejected', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Work', role: 'Accounting Clerk', desc: 'Argue why a $400 tab at a karaoke bar is a legitimate client entertainment expense.' },
  { id: 'wsk-12', title: 'Muted on Zoom', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Work', role: 'Impatient Client', desc: 'Apologize after giving a passionate 10-minute pitch while completely muted.' },
  { id: 'wsk-13', title: 'Reply All Catastrophe', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Work', role: 'IT Director', desc: 'Ask IT if it is possible to un-send a highly critical email you just blasted to the entire company.' },
  { id: 'wsk-14', title: 'Office Chair Theft', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Work', role: 'Rival Department Head', desc: 'Demand your ergonomic mesh chair back from the marketing department.' },
  { id: 'wsk-15', title: 'Unpaid Overtime', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Work', role: 'Project Manager', desc: 'Politely refuse to work the entire weekend for "company exposure and pizza."' }
];