import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packBravoTwoScenarios: ScenarioType[] = [
  { id: 'btw-01', title: 'Wrong Airport', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Travel', role: 'Confused Check-in Agent', desc: 'Realize at the counter that your flight departs from the other airport 40 miles away.' },
  { id: 'btw-02', title: 'Coffee on the Roof', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Incidents', role: 'Frantic Pedestrian', desc: 'Someone flags you down to tell you your coffee is still on the roof of your moving car.' },
  { id: 'btw-03', title: 'Middle Seat Armrest', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Travel', role: 'Aggressive Passenger', desc: 'Fight a silent, passive-aggressive elbow war over the middle seat armrest.' },
  { id: 'btw-04', title: 'Sleeping on Shoulder', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Travel', role: 'Startled Stranger', desc: 'Apologize profusely after waking up drooling on the shoulder of the person next to you.' },
  { id: 'btw-05', title: 'Missing the Ferry', originalLanguage: 'Greek', availableLanguages: ['Greek', 'English', 'French'], category: 'Travel', role: 'Ferry Captain', desc: 'Scream from the dock, begging the captain to turn the massive ferry around.' },
  { id: 'btw-06', title: 'Revolving Door Trap', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Incidents', role: 'Lobby Security', desc: 'Explain how you got your massive backpack wedged, stopping the revolving door entirely.' },
  { id: 'btw-07', title: 'Flat Tire in the Rain', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Incidents', role: 'Passing Motorist', desc: 'Beg a stranger in the pouring rain to help you loosen a rusted lug nut.' },
  { id: 'btw-08', title: 'Lost Subway Ticket', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Travel', role: 'Transit Police', desc: 'Try to prove you paid your fare after losing the tiny paper ticket on the train.' },
  { id: 'btw-09', title: 'Loud Phone on Train', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Everyday', role: 'Oblivious Commuter', desc: 'Politely ask the person next to you to stop watching TikToks at max volume without headphones.' },
  { id: 'btw-10', title: 'Broken Taxi Meter', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Travel', role: 'Shady Taxi Driver', desc: 'Argue the fare after realizing the driver "forgot" to turn the meter on 20 miles ago.' },
  { id: 'btw-11', title: 'Smuggling a Pet', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Travel', role: 'Suspicious Conductor', desc: 'Try to convince the train conductor that the barking from your jacket is just a ringtone.' },
  { id: 'btw-12', title: 'Express Train Mistake', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Travel', role: 'Fellow Passenger', desc: 'Panic when you realize you boarded the express train that skips your stop completely.' },
  { id: 'btw-13', title: 'Overbooked Bus', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Travel', role: 'Bus Conductor', desc: 'Refuse to share your single seat with another passenger on a fully packed bus.' },
  { id: 'btw-14', title: 'Forgot Passport', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Travel', role: 'Angry Partner', desc: 'Explain to your travel partner that you left your passport on the kitchen counter.' },
  { id: 'btw-15', title: 'Customs Confiscation', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Incidents', role: 'Customs Agent', desc: 'Argue that your sealed block of specialty cheese does not pose a threat to national security.' }
];