import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packKiloTwoScenarios: ScenarioType[] = [
  { id: 'ktw-01', title: 'Murim Cultivation Crash', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English', 'Mandarin'], category: 'Pop Culture', role: 'Sect Elder', desc: 'Explain that your Dantian shattered because you tried to mix Demonic and Orthodox martial arts.' },
  { id: 'ktw-03', title: 'Warframe Platinum Scam', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English', 'German'], category: 'Gaming', role: 'Trade Chat Scammer', desc: 'Call out a player trying to sell you a basic mod for 500 Platinum.' },
  { id: 'ktw-04', title: 'BlueString Power Scaling', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Pop Culture', role: 'Webtoon Elitist', desc: 'Aggressively debate whether the MC of Hanlim Gym could beat the MC of Study Group.' },
  { id: 'ktw-05', title: 'Combat Master Aimbot', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Gaming', role: 'Salty Opponent', desc: 'Laugh off accusations that your sniper flicks in Combat Master are from an aimbot.' },
  { id: 'ktw-06', title: 'Soundtrap Audio Clipping', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Music', role: 'Audio Engineer', desc: 'Argue that the audio clipping on your master track is "intentional aesthetic distortion."' },
  { id: 'ktw-08', title: 'Blood Strike Ping Spike', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Gaming', role: 'Squadmate', desc: 'Yell at your network provider while your squad gets wiped because your ping hit 999.' },
  { id: 'ktw-09', title: 'Nano Machine AI Glitch', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Pop Culture', role: 'Cheon Yeo-Woon', desc: 'Pretend you are debugging the Nano Machine AI while fighting a martial arts master.' },
  { id: 'ktw-10', title: 'The Stolen Killcam', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Gaming', role: 'Teammate', desc: 'Scream at your friend for stealing the final kill of the game right before your execution animation finished.' },
  { id: 'ktw-11', title: 'Absolute Sword Sense Lore', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Pop Culture', role: 'Confused Reader', desc: 'Try to explain the complex political factions of the Blood Cult to someone who just started reading.' },
  { id: 'ktw-12', title: 'Corrupted Project File', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Tech', role: 'Sympathetic Friend', desc: 'Cry about how your DAW crashed and corrupted a track you spent 40 hours mixing.' },
  { id: 'ktw-13', title: 'Cosplay Armor Break', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Incidents', role: 'Con Attendee', desc: 'Beg someone for duct tape after your EVA foam armor snaps in half in a crowded hallway.' },
  { id: 'ktw-14', title: 'Fallout New Vegas Crash', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Gaming', role: 'Modding Community', desc: 'Complain that you installed 200 mods and now the game crashes as soon as you leave Doc Mitchell\'s house.' }
];