import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packBravoScenarios: ScenarioType[] = [
  { id: 'brv-01', title: 'Corked Wine', originalLanguage: 'French', availableLanguages: ['French', 'Italian', 'English', 'Spanish'], category: 'Dining', role: 'Sommelier', desc: 'Politely inform the sommelier that the wine they just poured tastes corked.' },
  { id: 'brv-02', title: 'Expired Coupon', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Shopping', role: 'Cashier', desc: 'Argue that your 20% off coupon should still be valid since it expired yesterday.' },
  { id: 'brv-03', title: 'Vegan Menu Request', originalLanguage: 'German', availableLanguages: ['German', 'Dutch', 'English'], category: 'Dining', role: 'Waiter', desc: 'Ask if the kitchen can prepare a strict vegan meal not listed on the menu.' },
  { id: 'brv-04', title: 'Wrong Shoe Size', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'Korean', 'English'], category: 'Shopping', role: 'Shoe Salesman', desc: 'Ask the clerk to check the back room for a size 10 in the white colorway.' },
  { id: 'brv-05', title: 'Splitting the Bill', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English', 'Italian'], category: 'Dining', role: 'Waiter', desc: 'Ask to split the dinner bill evenly across four different credit cards.' },
  { id: 'brv-06', title: 'Buying a SIM Card', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'Arabic', 'English'], category: 'Shopping', role: 'Telecom Kiosk Worker', desc: 'Buy a prepaid tourist SIM card with at least 20GB of data.' },
  { id: 'brv-07', title: 'Dropping a Fork', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Dining', role: 'Restaurant Server', desc: 'Apologize for dropping your fork and ask for a clean one.' },
  { id: 'brv-08', title: 'Gift Receipt', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English', 'Japanese'], category: 'Shopping', role: 'Cashier', desc: 'Ask for a gift receipt and have the price tags removed from the item.' },
  { id: 'brv-09', title: 'Reserving for 10', originalLanguage: 'Italian', availableLanguages: ALL_LANGUAGES, category: 'Dining', role: 'Maitre D', desc: 'Call to reserve a table for 10 people for a birthday dinner this Friday.' },
  { id: 'brv-10', title: 'Testing a Mattress', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English', 'German'], category: 'Shopping', role: 'Furniture Salesman', desc: 'Ask about the firmness and warranty of a memory foam mattress.' },
  { id: 'brv-11', title: 'Cold Soup', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Dining', role: 'Chef', desc: 'Send your onion soup back to the kitchen because it was served ice cold.' },
  { id: 'brv-12', title: 'Out of Stock', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Shopping', role: 'Market Trader', desc: 'Ask when the trader will restock the specific brand of rice you want.' },
  { id: 'brv-13', title: 'Drive-Thru Broken', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Dining', role: 'Drive-Thru Worker', desc: 'Yell your order into a heavily distorted drive-thru speaker.' },
  { id: 'brv-14', title: 'High Chair Needed', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Dining', role: 'Hostess', desc: 'Ask if the restaurant can provide a high chair for a toddler.' },
  { id: 'brv-15', title: 'Returning a TV', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Shopping', role: 'Customer Service', desc: 'Return a flat-screen TV because it had dead pixels out of the box.' },
  { id: 'brv-16', title: 'The Catch of the Day', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'Spanish', 'English'], category: 'Dining', role: 'Fishmonger', desc: 'Ask what fish was caught this morning and how they recommend cooking it.' },
  { id: 'brv-17', title: 'Birthday Cake Order', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Shopping', role: 'Baker', desc: 'Order a custom chocolate cake with a specific name written in icing.' },
  { id: 'brv-18', title: 'Window Seat Request', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Dining', role: 'Hostess', desc: 'Ask if you can wait 15 minutes to be seated next to the window.' },
  { id: 'brv-19', title: 'Price Match', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Shopping', role: 'Electronics Manager', desc: 'Ask if the store will price-match a laptop you found cheaper online.' },
  { id: 'brv-20', title: 'Garlic Allergy', originalLanguage: 'Italian', availableLanguages: ALL_LANGUAGES, category: 'Dining', role: 'Waiter', desc: 'Explain that you are highly allergic to garlic in an Italian restaurant.' },
  { id: 'brv-21', title: 'Buying Fake AirPods', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Shopping', role: 'Street Vendor', desc: 'Haggle aggressively over the price of counterfeit wireless earbuds.' },
  { id: 'brv-22', title: 'Tap Water', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Dining', role: 'Waiter', desc: 'Refuse the expensive bottled water and explicitly ask for a carafe of tap water.' },
  { id: 'brv-23', title: 'Fitting Room Limit', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Shopping', role: 'Store Clerk', desc: 'Argue that you should be allowed to take 8 items into the fitting room, not 5.' },
  { id: 'brv-24', title: 'To-Go Box', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Dining', role: 'Waitress', desc: 'Ask for a container to pack your leftover fried chicken to go.' },
  { id: 'brv-25', title: 'No Cash', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Shopping', role: 'Street Hawker', desc: 'Explain you only have a card and ask if they accept bank transfers.' }
];