import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packUniformTwoScenarios: ScenarioType[] = [
  { id: 'utw-02', title: 'Asphalt Legends Paywall', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Gaming', role: 'Game Developer', desc: 'Draft an angry complaint to the devs about the aggressive pay-to-win mechanics in multiplayer.' },
  { id: 'utw-03', title: 'Sekiro Dodge Roll', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Gaming', role: 'Twitch Chat', desc: 'Argue with your chat that dodging is actually better than parrying for this specific boss.' },
  { id: 'utw-04', title: 'Missing VST Plugin', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Tech', role: 'Audio Engineer', desc: 'Panic because you opened an old project and your favorite chiptune synth VST is missing.' },
  { id: 'utw-05', title: 'Warframe Platinum Haggle', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Gaming', role: 'Trade Chat User', desc: 'Try to lowball a player selling a highly coveted Prime weapon blueprint.' },
  { id: 'utw-06', title: 'Blood Strike Ranked Throw', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Gaming', role: 'Ajxrhaider (You)', desc: 'Yell at your random teammates for pushing a full squad and immediately dying in a ranked match.' },
  { id: 'utw-07', title: 'Guitar String Snapped', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Incidents', role: 'Music Store Clerk', desc: 'Sprint into the store 5 minutes before a gig to buy a single high-E string.' },
  { id: 'utw-08', title: 'Audio Interface Latency', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Tech', role: 'Hardware Support', desc: 'Complain that your new USB audio interface has 500ms of latency while recording vocals.' },
  { id: 'utw-09', title: 'Over-Editing the Video', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Tech', role: 'Client', desc: 'Defend your decision to add 15 different CapCut transitions to a simple 30-second corporate video.' },
  { id: 'utw-10', title: 'Spoiled Webtoon Arc', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English', 'Korean'], category: 'Pop Culture', role: 'Forum Moderator', desc: 'Argue with a mod who banned you for posting untranslated raws of Nano Machine.' },
  { id: 'utw-11', title: 'Broken Microphone Stand', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Tech', role: 'Podcast Co-Host', desc: 'Try to record an entire podcast episode while physically holding a broken boom arm together.' },
  { id: 'utw-12', title: 'DJ Equipment Spill', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Incidents', role: 'Angry Club Manager', desc: 'Explain how a patron managed to spill a full vodka cranberry onto your DJ controller.' },
  { id: 'utw-14', title: 'Vinyl Record Warped', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Shopping', role: 'Record Store Owner', desc: 'Try to return a rare vinyl record that arrived completely warped from the heat.' },
  { id: 'utw-15', title: 'Stolen Sample', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Music', role: 'Rival Producer', desc: 'Accuse another producer of directly ripping your custom 808 bass slide without giving credit.' }
];