import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packYankeeTwoScenarios: ScenarioType[] = [
  { id: 'ykw-02', title: 'No Change in Danfo', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Travel', role: 'Bus Conductor', desc: 'Refuse to come down from the bus until the conductor gives you your 500 Naira change.' },
  { id: 'ykw-04', title: 'Fuel Scarcity Queues', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Incidents', role: 'Aggressive Driver', desc: 'Fight off a driver who is trying to cut ahead of you in a 3-hour petrol station queue.' },
  { id: 'ykw-05', title: 'Keke Napep Hustle', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Travel', role: 'Keke Driver', desc: 'Haggle the fare from Ado to the junction because he is trying to charge double for rain.' },
  { id: 'ykw-06', title: 'POS Decline Wahala', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Shopping', role: 'Supermarket Cashier', desc: 'Argue that you received a debit alert even though her POS machine says "Transaction Declined."' },
  { id: 'ykw-07', title: 'Omo-Onile Harassment', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Incidents', role: 'Street Thug (Agbero)', desc: 'Refuse to pay an illegal "parking fee" to a random guy on the street.' },
  { id: 'ykw-08', title: 'Generator Noise', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Everyday', role: 'Selfish Neighbor', desc: 'Beg your neighbor to turn off their massive diesel generator at 2 AM so you can sleep.' },
  { id: 'ykw-09', title: 'Amala Joint VIP', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Dining', role: 'Bukka Attendant', desc: 'Demand more Ewedu and extra assorted meat because you are a loyal regular customer.' },
  { id: 'ykw-10', title: 'Fake Police Checkpoint', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Incidents', role: 'Corrupt Officer', desc: 'Politely but firmly refuse to give a bribe because your car papers are perfectly complete.' },
  { id: 'ykw-11', title: 'NYSC Camp Food', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Dining', role: 'Kitchen Staff', desc: 'Complain that the watery beans and single slice of yam you were served is an insult.' },
  { id: 'ykw-12', title: 'The Fake Beggar', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Everyday', role: 'Professional Beggar', desc: 'Tell the guy with a "broken leg" that you literally saw him sprinting across the highway yesterday.' },
  { id: 'ykw-13', title: 'Overpriced Data Bundle', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Tech', role: 'Telecom Support', desc: 'Yell at customer care because your 10GB data bundle somehow finished in two hours.' },
  { id: 'ykw-14', title: 'The Wedding Rice', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Dining', role: 'Caterer', desc: 'Argue that as a friend of the groom, you deserve a takeaway pack of Jollof rice.' },
  { id: 'ykw-15', title: 'Fake Pastor Prediction', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Everyday', role: 'Street Preacher', desc: 'Politely walk away from a street prophet who insists you have an "evil spirit of poverty" following you.' }
];