import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packQuebecThreeScenarios: ScenarioType[] = [
  { id: 'qt3-01', title: 'Mars Rover Stuck', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Tech', role: 'NASA Director', desc: 'Explain that you accidentally drove the two-billion-dollar rover into a Martian ditch.' },
  { id: 'qt3-02', title: 'Event Horizon', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Incidents', role: 'Ship Computer', desc: 'Argue with the AI that flying directly into the black hole is a valid shortcut.' },
  { id: 'qt3-03', title: 'Asteroid Mining Rights', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Work', role: 'Rival Corporation', desc: 'Argue over who has the legal rights to mine a platinum asteroid floating in neutral space.' },
  { id: 'qt3-04', title: 'Alien Translation', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Tech', role: 'Galactic Ambassador', desc: 'Explain that the universal translator accidentally insulted the alien warlord\'s mother.' },
  { id: 'qt3-05', title: 'Spacewalk Tether Snap', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Incidents', role: 'Station Commander', desc: 'Radio in a panic because your tether snapped and you are slowly floating away from the ISS.' },
  { id: 'qt3-06', title: 'Dyson Sphere Delay', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Work', role: 'Stellar Architect', desc: 'Explain why the construction of the star-enclosing megastructure is 400 years behind schedule.' },
  { id: 'qt3-07', title: 'Intergalactic Toll Booth', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Travel', role: 'Alien Toll Operator', desc: 'Argue that you do not have exact change in space credits to use the hyper-lane.' },
  { id: 'qt3-08', title: 'Wormhole Traffic Jam', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Travel', role: 'Angry Pilot', desc: 'Honk your spaceship horn and yell at the pilot blocking the entrance to the wormhole.' },
  { id: 'qt3-09', title: 'Cryosleep Malfunction', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Incidents', role: 'Ship Medic', desc: 'Wake up 300 years too early and demand to be put back to sleep.' },
  { id: 'qt3-10', title: 'AI Ship Therapy', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Everyday', role: 'Depressed AI', desc: 'Act as a therapist for a highly advanced ship AI that feels unfulfilled opening doors.' },
  { id: 'qt3-11', title: 'Space Pirate Boarding', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Incidents', role: 'Pirate Captain', desc: 'Critique the space pirates\' boarding technique while they hold you at laser-point.' },
  { id: 'qt3-12', title: 'Zero Gravity Cooking', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Dining', role: 'Astronaut Chef', desc: 'Apologize for unleashing a cloud of floating soup droplets inside the space station.' },
  { id: 'qt3-13', title: 'Supernova Panic', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Incidents', role: 'Observatory Colleague', desc: 'Try to calmly explain that the sun they are looking at is about to explode in 5 minutes.' },
  { id: 'qt3-14', title: 'Moon Base Oxygen', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Tech', role: 'Base Engineer', desc: 'Report that someone left the front door to the moon base open and the air is escaping.' },
  { id: 'qt3-15', title: 'Galactic Filibuster', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Work', role: 'Senate Chancellor', desc: 'Attempt to filibuster a planetary destruction bill by reading a very long recipe for cake.' }
];