import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packHotelTwoScenarios: ScenarioType[] = [
  { id: 'htw-01', title: 'Ubuntu Display Drivers', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Tech', role: 'Linux Forum Mod', desc: 'Beg for help because your dual monitors stopped working after a random Ubuntu kernel update.' },
  { id: 'htw-02', title: 'The Forgotten BIOS Password', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Tech', role: 'IT Colleague', desc: 'Admit you locked yourself out of the BIOS on the main NOC monitoring rig.' },
  { id: 'htw-03', title: 'Overheated NVMe', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Tech', role: 'Hardware Tech', desc: 'Explain how your Kioxia Gen 4 SSD literally melted while compiling a massive C++ engine.' },
  { id: 'htw-04', title: 'Burp Suite False Alarm', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Tech', role: 'Security Chief', desc: 'Argue that the penetration test payload you intercepted is actually just a badly written API call.' },
  { id: 'htw-05', title: 'Dropped Production Table', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Tech', role: 'Lead DBA', desc: 'Try to blame a mysterious SQLmap injection for the database you accidentally dropped.' },
  { id: 'htw-06', title: 'Wi-Fi Password Crack', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Tech', role: 'Angry Landlord', desc: 'Deny using Hashcat and a captured handshake to steal the landlord\'s premium Wi-Fi.' },
  { id: 'htw-07', title: 'The Corrupted Repo', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Tech', role: 'Open Source Maintainer', desc: 'Apologize for force-pushing a broken commit that wiped out the last three days of the project.' },
  { id: 'htw-08', title: 'VPS Shutdown', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Tech', role: 'Hosting Provider', desc: 'Argue with customer support who shut down your VPS for "excessive CPU usage" during a render.' },
  { id: 'htw-09', title: 'Thermal Paste Disaster', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Tech', role: 'PC Repair Tech', desc: 'Explain why you used an entire tube of thermal paste and shorted out the motherboard.' },
  { id: 'htw-10', title: 'The Rogue Python Script', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Tech', role: 'Cloud Admin', desc: 'Apologize for a script that accidentally sent 10,000 automated emails to a single client.' },
  { id: 'htw-11', title: 'Keyboard Switch Swap', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Tech', role: 'Custom Keeb Nerd', desc: 'Argue that linear switches are objectively terrible for actual software development.' },
  { id: 'htw-12', title: 'Dead Pixels', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Shopping', role: 'Monitor Salesman', desc: 'Demand an exchange because the monitor has exactly one dead pixel directly in the center.' },
  { id: 'htw-13', title: 'Bluetooth Interference', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Tech', role: 'Roommate', desc: 'Demand they turn off their microwave because it is destroying your wireless headphone signal.' },
  { id: 'htw-14', title: 'The Missing Sudoer', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Tech', role: 'Sysadmin', desc: 'Beg the admin to add you back to the sudoers file after your privileges were revoked.' },
  { id: 'htw-15', title: 'Docker Container Crash', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Tech', role: 'DevOps Lead', desc: 'Explain that the container didn\'t fail, it was just "gracefully restarting forever."' }
];