import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packRomeoTwoScenarios: ScenarioType[] = [
  { id: 'rtw-01', title: 'NYSC State Relocation', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Work', role: 'State Coordinator', desc: 'Plead your case for an urgent NYSC state relocation based on entirely fabricated health grounds.' },
  { id: 'rtw-02', title: 'Nepa Cut the Light', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Everyday', role: 'Prepaid Meter Agent', desc: 'Argue that you loaded your prepaid meter yesterday and your power shouldn\'t be disconnected.' },
  { id: 'rtw-03', title: 'Leaky Roof Dispute', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Incidents', role: 'Cheap Landlord', desc: 'Demand your landlord fix the gaping hole in the roof that is flooding your living room.' },
  { id: 'rtw-04', title: 'Locked Out by Roommate', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Everyday', role: 'Heavy Sleeper Roommate', desc: 'Yell through the window trying to wake up your roommate who bolted the door from the inside.' },
  { id: 'rtw-05', title: 'Lost House Keys', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Incidents', role: 'Expensive Locksmith', desc: 'Haggle with a 24-hour locksmith trying to charge you 300 euros to drill your deadbolt.' },
  { id: 'rtw-06', title: 'Washing Machine Flooded', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Incidents', role: 'Downstairs Neighbor', desc: 'Apologize to your neighbor because your washing machine just flooded their ceiling.' },
  { id: 'rtw-07', title: 'Internet Installation Delay', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Everyday', role: 'ISP Dispatcher', desc: 'Scream at your ISP because the installation tech missed the 8-hour arrival window.' },
  { id: 'rtw-08', title: 'Missing Package Claim', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Incidents', role: 'Courier Support', desc: 'Prove that the "delivered" photo shows a front porch that is absolutely not yours.' },
  { id: 'rtw-09', title: 'Aggressive Door-to-Door Sales', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Everyday', role: 'Persistent Salesman', desc: 'Politely try to close your front door on a salesman who refuses to take no for an answer.' },
  { id: 'rtw-10', title: 'Stray Cat Invasion', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Everyday', role: 'Animal Control', desc: 'Explain that a stray cat got into your house and is now fiercely guarding your refrigerator.' },
  { id: 'rtw-11', title: 'Power Tool Noise', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Everyday', role: 'DIY Neighbor', desc: 'Ask the neighbor to please stop using a masonry drill on the shared wall at 6 AM.' },
  { id: 'rtw-12', title: 'Trash Sorting Fine', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Incidents', role: 'Sanitation Officer', desc: 'Argue your way out of a municipal fine for putting a cardboard box in the plastic bin.' },
  { id: 'rtw-13', title: 'Stuck in the Garage', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Incidents', role: 'Mechanic', desc: 'Call for help because the automatic garage door spring snapped and you are trapped inside.' },
  { id: 'rtw-14', title: 'The Broken Boiler', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Everyday', role: 'Plumber', desc: 'Explain that your water heater is making a sound like a jet engine about to explode.' },
  { id: 'rtw-15', title: 'Barking Dog Complaint', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Everyday', role: 'Defensive Pet Owner', desc: 'Politely inform your neighbor that their dog has been barking non-stop for 14 hours.' }
];