import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packZuluScenarios: ScenarioType[] = [
  { id: 'zul-01', title: 'Dragon Hoard Negotiation', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Funny', role: 'Ancient Dragon', desc: 'Try to convince a dragon to let you take just one gold coin to pay off your student loans.' },
  { id: 'zul-02', title: 'Time Machine Broken', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Funny', role: 'Angry Time Cop', desc: 'Explain why you parked your DeLorean in the middle of a medieval battlefield.' },
  { id: 'zul-03', title: 'Spaceship Parking Ticket', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Funny', role: 'Intergalactic Meter Maid', desc: 'Argue that the "No Hovering" sign in the asteroid belt was obscured by space dust.' },
  { id: 'zul-04', title: 'Magic Wand Misfire', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Funny', role: 'Disappointed Wizard', desc: 'Explain why your attempt to summon a fireball resulted in a shower of aggressive rubber ducks.' },
  { id: 'zul-05', title: 'Zombie Bite Hidden', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Funny', role: 'Paranoid Survivor', desc: 'Convince the group leader that the bite mark on your arm is just a really bad mosquito bite.' },
  { id: 'zul-06', title: 'Cybernetics Glitch', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Funny', role: 'Ripperdoc', desc: 'Complain that your new cybernetic arm keeps trying to high-five people against your will.' },
  { id: 'zul-07', title: 'Vampire Sunburn', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Funny', role: 'Beach Lifeguard', desc: 'Demand SPF 10,000 sunscreen because you are literally bursting into flames.' },
  { id: 'zul-08', title: 'AI Uprising', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Tech', role: 'Sentient Smart Fridge', desc: 'Negotiate for your life with a refrigerator that has locked your food away until you praise it.' },
  { id: 'zul-09', title: 'Prophecy Misinterpreted', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Funny', role: 'High Priest', desc: 'Explain that you are just an IT guy, not the "Chosen One" meant to slay the Dark Lord.' },
  { id: 'zul-10', title: 'Haunted Sword', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Funny', role: 'Cursed Weapon', desc: 'Beg the magical sword you just looted to stop loudly criticizing your combat forms.' },
  { id: 'zul-11', title: 'Superhero Cape Stuck', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Funny', role: 'Civilian Bystander', desc: 'Ask a random person to help untangle your majestic cape from a revolving door.' },
  { id: 'zul-12', title: 'Alien Probing Complaint', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Funny', role: 'UFO Customer Service', desc: 'File a formal grievance about the lack of bedside manner during your recent alien abduction.' },
  { id: 'zul-13', title: 'Wizard Duel Argument', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Funny', role: 'Rival Sorcerer', desc: 'Argue over the official rulebook after your opponent casts a spell that is clearly banned.' },
  { id: 'zul-14', title: 'Space Station Airlock', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Funny', role: 'AI Computer', desc: 'Plead with the station AI to open the pod bay doors because you forgot your space keys.' },
  { id: 'zul-15', title: 'Potion Tastes Awful', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Funny', role: 'Alchemist', desc: 'Complain that the potion of eternal life tastes exactly like expired cough syrup.' }
];