import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packTangoTwoScenarios: ScenarioType[] = [
  { id: 'ttw-01', title: 'Late Assignment Panic', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Work', role: 'Strict Professor', desc: 'Beg your professor to accept an essay 4 minutes past the midnight portal deadline.' },
  { id: 'ttw-02', title: 'The Group Project Carry', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Work', role: 'Lazy Partner', desc: 'Confront the group member who contributed absolutely nothing to the final presentation.' },
  { id: 'ttw-03', title: 'Lost Exam Paper', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Work', role: 'Confused TA', desc: 'Argue that you definitely handed in your midterm, and the TA must have lost it.' },
  { id: 'ttw-04', title: 'Library Fine Evasion', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Everyday', role: 'Stern Librarian', desc: 'Try to waive a $40 library fine for a textbook you swear you returned last month.' },
  { id: 'ttw-05', title: 'Wrong Lecture Hall', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Everyday', role: 'Professor', desc: 'Try to quietly sneak out after realizing you sat through 30 minutes of advanced quantum mechanics by mistake.' },
  { id: 'ttw-06', title: 'Scholarship Interview', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Work', role: 'Dean of Admissions', desc: 'Persuade the Dean that your side project, a massive RPG AI Tutor, makes you the perfect candidate.' },
  { id: 'ttw-07', title: 'Dorm Room Inspection', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Incidents', role: 'RA (Resident Advisor)', desc: 'Explain away the unauthorized hot plate and toaster oven hidden under your bed.' },
  { id: 'ttw-08', title: 'Plagiarism Bot False Positive', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Work', role: 'Academic Panel', desc: 'Prove that the Turnitin software flagged your completely original work as 90% AI-generated.' },
  { id: 'ttw-09', title: 'Graduation Ticket Shortage', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Everyday', role: 'Registrar', desc: 'Beg for two extra graduation tickets so your grandparents don\'t have to watch from the parking lot.' },
  { id: 'ttw-10', title: 'Course Registration Crash', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Tech', role: 'IT Helpdesk', desc: 'Scream at IT because the student portal crashed exactly when registration opened.' },
  { id: 'ttw-11', title: 'Overpriced Textbooks', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Shopping', role: 'Campus Bookstore', desc: 'Argue about paying $300 for a textbook that was authored by the professor teaching the class.' },
  { id: 'ttw-12', title: 'Cafeteria Food Poisoning', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Dining', role: 'Cafeteria Manager', desc: 'Complain that the campus dining hall meat pie gave you food poisoning during finals week.' },
  { id: 'ttw-13', title: 'The Unfair Curve', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Work', role: 'Calculus Professor', desc: 'Argue that curving a test where the highest score was a 45% is fundamentally broken.' },
  { id: 'ttw-14', title: 'Locked out of Dorm', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Incidents', role: 'Campus Security', desc: 'Convince security to unlock your door at 3 AM because your roommate went home for the weekend.' },
  { id: 'ttw-15', title: 'The Thesis Defense', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Work', role: 'Thesis Committee', desc: 'Defend your highly unconventional thesis topic against a panel of very traditional academics.' }
];