import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packGolfTwoScenarios: ScenarioType[] = [
  { id: 'gtw-01', title: 'NYSC Clearance Drama', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Work', role: 'Strict LGI', desc: 'Beg your Local Government Inspector to sign your monthly clearance even though you are two days late.' },
  { id: 'gtw-02', title: 'The Endless Voix Meeting', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Work', role: 'Director of Admin', desc: 'Try to gracefully exit a Zoom meeting that was supposed to end 45 minutes ago.' },
  { id: 'gtw-03', title: 'Stolen Office Pen', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Work', role: 'Suspicious Coworker', desc: 'Fiercely interrogate the colleague you suspect of stealing your favorite Pilot G2 pen.' },
  { id: 'gtw-04', title: 'Microwave Fish', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Work', role: 'Offended Colleague', desc: 'Defend your right to microwave leftover tilapia in the communal office breakroom.' },
  { id: 'gtw-05', title: 'Voix ERP Feature Creep', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Tech', role: 'Ambitious Manager', desc: 'Politely explain why adding a built-in social network to the company ERP is a terrible idea.' },
  { id: 'gtw-06', title: 'The Reply-All Apology', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Work', role: 'Company CEO', desc: 'Explain why you accidentally emailed a meme about being underpaid to the entire executive board.' },
  { id: 'gtw-07', title: 'Unpaid Internship', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Work', role: 'Exploitative Boss', desc: 'Argue that "valuable industry experience" does not actually pay your rent.' },
  { id: 'gtw-08', title: 'Broken Printer Protocol', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Work', role: 'Office Manager', desc: 'Deny all knowledge of jamming the office printer with heavy-duty cardstock.' },
  { id: 'gtw-09', title: 'Holiday Leave Denied', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Work', role: 'HR Rep', desc: 'Fight for your approved time off after HR "accidentally" deletes the record from the system.' },
  { id: 'gtw-10', title: 'Desk Reassignment', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Work', role: 'Facilities Manager', desc: 'Complain that your new desk is located right next to the incredibly loud server room.' },
  { id: 'gtw-11', title: 'The CC BCC Mixup', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Work', role: 'Angry Client', desc: 'Damage control after you accidentally CC\'d a client on an internal email insulting their demands.' },
  { id: 'gtw-12', title: 'Coffee Fund Freeloader', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Work', role: 'Office Enforcer', desc: 'Argue that you shouldn\'t have to pay into the coffee fund because you only drink water.' },
  { id: 'gtw-13', title: 'Inappropriate Slack Emoji', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Work', role: 'Confused Boomer Boss', desc: 'Explain the actual meaning of the skull emoji you just reacted to their message with.' },
  { id: 'gtw-14', title: 'The Promotion Snub', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Work', role: 'Direct Supervisor', desc: 'Demand an explanation for why the new hire got the Web Admin role over you.' },
  { id: 'gtw-15', title: 'Working Through Lunch', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Work', role: 'Workaholic Peer', desc: 'Try to convince your peer that eating at your desk does not make you a superior employee.' }
];