import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packVictorScenarios: ScenarioType[] = [
  { id: 'vic-01', title: 'Makina Tempo Dispute', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English', 'German'], category: 'Music', role: 'Club DJ', desc: 'Argue that pushing the BPM to 180 for a Makina track is absolutely necessary for the set.' },
  { id: 'vic-02', title: 'Brazilian Phonk Bass', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Music', role: 'Audio Engineer', desc: 'Explain how to properly distort the 808s in a Brazilian Phonk track without blowing out the speakers.' },
  { id: 'vic-03', title: 'Soundtrap CPU Limits', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Tech', role: 'Fellow Producer', desc: 'Complain that Soundtrap is crashing because your browser tab is using 6GB of RAM.' },
  { id: 'vic-04', title: 'PipeWire Mono Config', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Tech', role: 'Audiophile', desc: 'Defend your custom bash script that forces PipeWire to output audio in mono on Ubuntu.' },
  { id: 'vic-05', title: 'John Hizaki Alias', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Music', role: 'A&R Rep', desc: 'Pitch your electronic music portfolio under the John Hizaki alias to a record label.' },
  { id: 'vic-06', title: '8-Bit Chiptune Plugins', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Music', role: 'Retro Gamer', desc: 'Discuss which VST plugins perfectly replicate the sound of a vintage Game Boy.' },
  { id: 'vic-07', title: 'DaVinci Resolve Rendering', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Tech', role: 'Video Editor', desc: 'Complain about DaVinci Resolve utilizing 100% of your GPU during a simple color grade export.' },
  { id: 'vic-08', title: 'HandBrake Compression', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Tech', role: 'Archivist', desc: 'Argue about the optimal HandBrake settings to compress a 4K video without visible artifacting.' },
  { id: 'vic-09', title: 'CapCut Watermark', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Tech', role: 'Content Creator', desc: 'Help a friend figure out how to export their TikTok edit from CapCut without the giant watermark.' },
  { id: 'vic-10', title: 'Adobe Audition Noise Reduction', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Tech', role: 'Podcast Host', desc: 'Explain how to use Adobe Audition to remove the aggressive background fan noise from a vocal track.' },
  { id: 'vic-11', title: 'Dead Headphones', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Shopping', role: 'Gadget Vendor', desc: 'Try to return studio headphones that only play audio out of the left ear.' },
  { id: 'vic-12', title: 'Copyright Takedown', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Work', role: 'YouTube Support', desc: 'Fight a false copyright claim on a track you produced entirely from scratch.' },
  { id: 'vic-13', title: 'The Blown Speaker', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Incidents', role: 'Event Manager', desc: 'Explain how your aggressive Juke bass drop managed to blow out the venue\'s main subwoofer.' },
  { id: 'vic-14', title: 'Missing Project File', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Tech', role: 'Desperate Friend', desc: 'Panic because your DAW crashed and the project file is now completely corrupted.' },
  { id: 'vic-15', title: 'Spotify Algorithm', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Music', role: 'Indie Artist', desc: 'Rant about how the Spotify algorithm completely ignored your latest highly produced single.' }
];