import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packYankeeScenarios: ScenarioType[] = [
  { id: 'ynk-01', title: 'Ski Lift Stuck', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Travel', role: 'Stranded Skier', desc: 'Panic with the stranger sitting next to you as the ski lift stops dangling 100 feet in the air.' },
  { id: 'ynk-02', title: 'Dropped Phone Skydiving', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Incidents', role: 'Tandem Instructor', desc: 'Yell over the wind that you just dropped your unlocked phone at 10,000 feet.' },
  { id: 'ynk-03', title: 'Bungee Jump Hesitation', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Travel', role: 'Jump Master', desc: 'Stand on the edge of the bridge and try to negotiate a refund because you changed your mind.' },
  { id: 'ynk-04', title: 'Paintball Friendly Fire', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Everyday', role: 'Angry Teammate', desc: 'Apologize profusely for shooting your own team captain in the back of the helmet.' },
  { id: 'ynk-05', title: 'Go-Kart Ramming', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Everyday', role: 'Track Marshal', desc: 'Defend yourself after being black-flagged for aggressively ramming other go-karts.' },
  { id: 'ynk-06', title: 'Cave Diving Panic', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Incidents', role: 'Dive Master', desc: 'Signal frantically that you want to go back up because it is too dark and cramped.' },
  { id: 'ynk-07', title: 'Zipline Stuck', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Incidents', role: 'Rescue Guide', desc: 'Hang suspended in the middle of a jungle canyon while a guide slowly climbs out to push you.' },
  { id: 'ynk-08', title: 'White Water Flip', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Travel', role: 'Raft Guide', desc: 'Yell at the guide after the raft flips and sends you swimming down a level 4 rapid.' },
  { id: 'ynk-09', title: 'Rock Climbing Cramp', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Everyday', role: 'Belayer', desc: 'Scream down to your partner that your forearm cramped and you are about to fall.' },
  { id: 'ynk-10', title: 'Machine Hog', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Everyday', role: 'Gym Influencer', desc: 'Tell a vlogger they cannot reserve three different cable machines while filming a TikTok.' },
  { id: 'ynk-11', title: 'Dodgeball Headshot', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Everyday', role: 'Furious Opponent', desc: 'Apologize for accidentally throwing a dodgeball directly into someone\'s face at mach 3.' },
  { id: 'ynk-12', title: 'Lost in the Woods', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Incidents', role: 'Park Ranger', desc: 'Call rescue services to explain you wandered off the trail to take a photo and are now completely lost.' },
  { id: 'ynk-13', title: 'Surfing Wipeout', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Everyday', role: 'Angry Local Surfer', desc: 'Apologize for dropping in on their wave and crashing your foam board into theirs.' },
  { id: 'ynk-14', title: 'Skatepark Poser', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Everyday', role: 'Teenage Skater', desc: 'Try to play it cool after completely wiping out while trying to do a basic ollie.' },
  { id: 'ynk-15', title: 'Marathon Exhaustion', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Everyday', role: 'Water Station Volunteer', desc: 'Beg for a ride to the finish line because you hit the wall at mile 18.' }
];