import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packTangoScenarios: ScenarioType[] = [
  { id: 'tgo-01', title: 'Nmap Aggressive Scan', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Tech', role: 'Suspicious IT Director', desc: 'Explain why you were running a -A Nmap scan on the primary corporate subnet.' },
  { id: 'tgo-02', title: 'Burp Suite Intercept', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Tech', role: 'Web Developer', desc: 'Show a developer how you easily bypassed their client-side validation using Burp Suite.' },
  { id: 'tgo-03', title: 'SQLmap False Positive', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Tech', role: 'Database Admin', desc: 'Argue that SQLmap is throwing a false positive and the database is actually secure.' },
  { id: 'tgo-04', title: 'Cracking Hashcat', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Tech', role: 'Cybersecurity Student', desc: 'Debate the efficiency of John the Ripper versus Hashcat for offline password cracking.' },
  { id: 'tgo-05', title: 'Wifite Neighborhood', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Tech', role: 'Angry Neighbor', desc: 'Deny that you used Wifite to deauth and capture their Wi-Fi handshake.' },
  { id: 'tgo-06', title: 'Bettercap Spoofing', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Tech', role: 'Cafe Owner', desc: 'Explain why you are running ARP spoofing tests on the public cafe network.' },
  { id: 'tgo-07', title: 'Hydra Brute Force', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Tech', role: 'Cloud Admin', desc: 'Explain why your IP address triggered 400 failed SSH login attempts on the server.' },
  { id: 'tgo-08', title: 'Searchsploit Dive', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Tech', role: 'Bug Bounty Hunter', desc: 'Discuss an ancient CVE you just pulled up using Searchsploit that affects a major router brand.' },
  { id: 'tgo-09', title: 'Recon-ng OSINT', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Tech', role: 'Privacy Advocate', desc: 'Show someone exactly how much of their personal data you scraped using basic OSINT tools.' },
  { id: 'tgo-10', title: 'Kali Linux Flex', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Tech', role: 'Windows User', desc: 'Mock a friend who thinks hacking is just changing their terminal text to neon green.' },
  { id: 'tgo-11', title: 'The Phishing Test', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Work', role: 'Gullible Co-worker', desc: 'Explain to your coworker that they just failed the company\'s internal phishing simulation.' },
  { id: 'tgo-12', title: 'Stolen Passwords', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Incidents', role: 'Clueless Friend', desc: 'Convince your friend they need to change their password because "Password123" was found in a data breach.' },
  { id: 'tgo-13', title: 'Social Engineering', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Work', role: 'Security Guard', desc: 'Try to social engineer your way into the server room carrying a clipboard and a ladder.' },
  { id: 'tgo-14', title: 'Ransomware Recovery', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Tech', role: 'CISO', desc: 'Discuss whether you should pay the hackers or attempt to restore from an infected backup.' },
  { id: 'tgo-15', title: 'Rogue USB Drive', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Tech', role: 'Curious Employee', desc: 'Yell at an employee for plugging a random USB drive they found in the parking lot into the network.' }
];