import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packSierraTwoScenarios: ScenarioType[] = [
  { id: 'stw-01', title: 'Next.js 16.3 Turbopack', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Tech', role: 'Junior Dev', desc: 'Explain to a Junior Dev why Turbopack in Next.js 16.3 is vastly outperforming their Webpack setup.' },
  { id: 'stw-02', title: 'Groq SDK Rate Limit', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Tech', role: 'API Support', desc: 'Beg Groq support to increase your token limit because your RPG Tutor app is scaling too fast.' },
  { id: 'stw-03', title: 'Tailwind v4 Config', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Tech', role: 'UI Designer', desc: 'Defend your decision to migrate the entire project to the new Tailwind CSS v4 engine.' },
  { id: 'stw-04', title: 'Database Migration Fail', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Tech', role: 'Furious DBA', desc: 'Admit that your script accidentally dropped all foreign keys during the production migration.' },
  { id: 'stw-05', title: 'GitHub Force Push', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Tech', role: 'Tech Lead', desc: 'Explain why you used `git push origin main --force` and wiped out the team\'s morning commits.' },
  { id: 'stw-06', title: 'Corrupted Node Modules', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Tech', role: 'Frustrated Colleague', desc: 'Tell your coworker that their problem will be solved if they just delete `node_modules` and run npm install.' },
  { id: 'stw-07', title: 'Localhost Only Bug', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Tech', role: 'QA Tester', desc: 'Argue that the bug they found must be a cache issue because "it works on my machine."' },
  { id: 'stw-08', title: 'Sudo Rm -rf', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Tech', role: 'Panicked Sysadmin', desc: 'Call your boss to explain you accidentally wiped the root directory of the Ubuntu staging server.' },
  { id: 'stw-09', title: 'Docker Container Sprawl', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Tech', role: 'Cloud Architect', desc: 'Explain why your local machine has 45 orphaned Docker containers running simultaneously.' },
  { id: 'stw-10', title: 'Forgetting the Env File', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Tech', role: 'Angry Teammate', desc: 'Apologize for pushing an update that breaks the app because you didn\'t commit the new `.env` variables.' },
  { id: 'stw-11', title: 'Vercel Deployment Hang', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Tech', role: 'Client', desc: 'Stall a client on a call while frantically watching Vercel hang on the "Building" step for 15 minutes.' },
  { id: 'stw-12', title: 'The Regex Nightmare', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Tech', role: 'Code Reviewer', desc: 'Defend a completely unreadable 400-character Regular Expression you wrote to validate email addresses.' },
  { id: 'stw-13', title: 'Browser Caching Issue', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Tech', role: 'Confused User', desc: 'Try to explain the concept of performing a "Hard Refresh" to a user who refuses to clear their cache.' },
  { id: 'stw-14', title: 'Uncommented Code', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Tech', role: 'New Developer', desc: 'Apologize to the new hire for handing them a 2,000-line Python script with zero comments.' },
  { id: 'stw-15', title: 'The Infinite Render Loop', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Tech', role: 'React Engineer', desc: 'Explain how your `useEffect` hook accidentally created an infinite render loop and crashed the browser.' }
];