import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packAlphaTwoScenarios: ScenarioType[] = [
  { id: 'atw-01', title: 'Demanding the Manager', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Shopping', role: 'Retail Manager', desc: 'Defend your cashier from an incredibly entitled customer screaming about an expired policy.' },
  { id: 'atw-02', title: 'Card Declined', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Shopping', role: 'Impatient Cashier', desc: 'Frantically transfer funds on your phone while a huge line forms behind you.' },
  { id: 'atw-03', title: 'Out of Stock Rage', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Shopping', role: 'Disappointed Customer', desc: 'Explain to a customer that you cannot magically spawn the sold-out item from the back room.' },
  { id: 'atw-04', title: 'Mannequin Jumpscare', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Shopping', role: 'Security Guard', desc: 'Apologize for screaming and punching a highly realistic mannequin in a dark corner of the store.' },
  { id: 'atw-05', title: 'Closing Time Lingerer', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Shopping', role: 'Store Clerk', desc: 'Politely hint to a customer that the store closed 20 minutes ago and they need to leave.' },
  { id: 'atw-06', title: 'Spilled Display', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Incidents', role: 'Grocery Store Manager', desc: 'Apologize profusely after your shopping cart annihilated a pyramid of glass tomato sauce jars.' },
  { id: 'atw-07', title: 'Shoplifting Accusation', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Incidents', role: 'Loss Prevention', desc: 'Prove that the item in your pocket is yours and you didn\'t steal it from the shelf.' },
  { id: 'atw-08', title: 'Drive-Thru Static', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Dining', role: 'Fast Food Worker', desc: 'Try to order food while a massive truck idles next to you and drowns out the speaker.' },
  { id: 'atw-09', title: 'Secret Shopper Panic', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Work', role: 'Nervous Coworker', desc: 'Warn your coworker that the person asking highly specific questions is definitely corporate.' },
  { id: 'atw-10', title: 'Black Friday Stampede', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Shopping', role: 'Rival Shopper', desc: 'Argue over who grabbed the last discounted flat-screen TV first.' },
  { id: 'atw-11', title: 'Return Without Receipt', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Shopping', role: 'Customer Service', desc: 'Try to return a clearly used blender without the box, the receipt, or the lid.' },
  { id: 'atw-12', title: 'Gift Wrapping Disaster', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Shopping', role: 'Mall Wrapper', desc: 'Ask them to re-wrap the present because they accidentally wrapped your car keys inside it.' },
  { id: 'atw-13', title: 'Restroom Key Lost', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Incidents', role: 'Gas Station Attendant', desc: 'Confess that you accidentally dropped the giant wooden restroom key into the toilet.' },
  { id: 'atw-14', title: 'The Penny Pincher', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Shopping', role: 'Tired Cashier', desc: 'Pay for a $14 transaction entirely in loose, unrolled coins.' },
  { id: 'atw-15', title: 'Self-Checkout Error', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Shopping', role: 'Attendant', desc: 'Wave down an employee because the machine insists there is an "unexpected item in the bagging area."' }
];