import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packQuebecScenarios: ScenarioType[] = [
  { id: 'que-01', title: 'Lost Passport in Transit', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English', 'French'], category: 'Travel', role: 'Embassy Official', desc: 'Frantically explain that you left your passport on a high-speed train and your flight is in 4 hours.' },
  { id: 'que-02', title: 'Attacked by Macaques', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English', 'Mandarin'], category: 'Incidents', role: 'Park Medic', desc: 'Explain how a gang of wild monkeys ambushed you and stole your backpack in Kyoto.' },
  { id: 'que-03', title: 'Avalanche Warning', originalLanguage: 'German', availableLanguages: ['German', 'English', 'Italian'], category: 'Travel', role: 'Ski Patrol', desc: 'Argue that you are an expert skier and should be allowed past the avalanche barricades.' },
  { id: 'que-04', title: 'Fake Tour Guide Scam', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English', 'Russian'], category: 'Incidents', role: 'Tourist Police', desc: 'Report a "guide" who took your money, walked you into an alley, and completely vanished.' },
  { id: 'que-05', title: 'Stranded on an Island', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Travel', role: 'Ferry Captain', desc: 'Beg a passing boat to let you board after missing the final ferry back to the mainland.' },
  { id: 'que-06', title: 'Jellyfish Sting', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English', 'Spanish'], category: 'Incidents', role: 'Lifeguard', desc: 'Limp up to the lifeguard stand asking for vinegar because you just swam into a massive jellyfish.' },
  { id: 'que-07', title: 'The Overweight Backpacker', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Travel', role: 'Budget Airline Agent', desc: 'Try to wear 7 layers of clothing to avoid paying the exorbitant baggage fee.' },
  { id: 'que-08', title: 'Lost in the Catacombs', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Travel', role: 'Tour Group Straggler', desc: 'Panic with a fellow tourist after realizing your guide left you behind in a dark tunnel.' },
  { id: 'que-09', title: 'Venomous Snake in Room', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Incidents', role: 'Hotel Concierge', desc: 'Demand a new room immediately because there is a massive snake coiled around the toilet.' },
  { id: 'que-10', title: 'Rental Car in a River', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Incidents', role: 'Rental Insurance Agent', desc: 'Explain that the GPS explicitly told you to drive straight into the canal.' },
  { id: 'que-11', title: 'Stowaway Animal', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Travel', role: 'Customs Inspector', desc: 'Swear that you have no idea how a live iguana got into your checked luggage.' },
  { id: 'que-12', title: 'Altitude Sickness', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Incidents', role: 'Mountain Guide', desc: 'Admit that you cannot breathe and need to descend immediately from the summit.' },
  { id: 'que-13', title: 'Stolen Shoes at Temple', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English', 'Japanese'], category: 'Incidents', role: 'Temple Monk', desc: 'Explain that someone stole your expensive sneakers from the rack while you were praying.' },
  { id: 'que-14', title: 'Fake Airbnb Listing', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English', 'Arabic'], category: 'Travel', role: 'Confused Homeowner', desc: 'Knock on a door claiming you rented this apartment, only to find the actual owner living there.' },
  { id: 'que-15', title: 'Sleeping in the Airport', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Travel', role: 'Security Guard', desc: 'Beg the guard not to kick you out of the terminal while you wait for a 6 AM budget flight.' }
];