import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packQuebecTwoScenarios: ScenarioType[] = [
  { id: 'qtw-01', title: 'Undercooked Chicken', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Dining', role: 'Defensive Chef', desc: 'Firmly explain that your chicken is raw in the middle and completely inedible.' },
  { id: 'qtw-02', title: 'Wrong Milk Type', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Dining', role: 'Barista', desc: 'Argue that you specifically asked for oat milk because you are severely lactose intolerant.' },
  { id: 'qtw-03', title: 'No Utensils Included', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Dining', role: 'Delivery Driver', desc: 'Demand to know how you are supposed to eat soup in a hotel room with no spoon.' },
  { id: 'qtw-04', title: 'Missing Drive-Thru Item', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Dining', role: 'Window Worker', desc: 'Hold up the drive-thru line because they forgot your 10-piece chicken nuggets.' },
  { id: 'qtw-05', title: 'Vending Machine Thief', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Everyday', role: 'Janitor', desc: 'Beg for the keys to the vending machine because it just stole your last two dollars.' },
  { id: 'qtw-06', title: 'Expired Coupon Scan', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Shopping', role: 'Strict Cashier', desc: 'Argue that the store app glitched and your 50% off coupon should still apply.' },
  { id: 'qtw-07', title: 'Wrong Shoe Box', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Shopping', role: 'Store Clerk', desc: 'Return to the store because the clerk gave you two left shoes in the box.' },
  { id: 'qtw-08', title: 'Broken Fitting Room Door', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Shopping', role: 'Retail Worker', desc: 'Yell for help because the lock jammed and you are trapped inside the fitting room.' },
  { id: 'qtw-09', title: 'Self-Checkout Scale', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Shopping', role: 'Tired Attendant', desc: 'Explain that you placed the item in the bagging area but the machine is still screaming at you.' },
  { id: 'qtw-10', title: 'Refusing Cash', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Shopping', role: 'Cashier', desc: 'Argue with a "card-only" establishment when all you have is a crisp $100 bill.' },
  { id: 'qtw-11', title: 'Melted Ice Cream Delivery', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Dining', role: 'Delivery Rider', desc: 'Complain that your ice cream order arrived as lukewarm soup.' },
  { id: 'qtw-12', title: 'Dropping the Cake', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Shopping', role: 'Bakery Owner', desc: 'Beg the bakery to fix a birthday cake you just dropped face-first on the sidewalk.' },
  { id: 'qtw-13', title: 'Stolen Grocery Cart', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Everyday', role: 'Oblivious Shopper', desc: 'Confront the shopper who accidentally walked away with your half-full grocery cart.' },
  { id: 'qtw-14', title: 'Fake Leather Bag', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Shopping', role: 'Market Vendor', desc: 'Call out a vendor selling a "genuine leather" bag that is clearly shedding plastic.' },
  { id: 'qtw-15', title: 'The Silent Barber', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Everyday', role: 'Intimidating Barber', desc: 'Try to guide a completely silent, terrifyingly fast barber to not cut your hair too short.' }
];