import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packEchoThreeScenarios: ScenarioType[] = [
  { id: 'et3-02', title: 'Danfo Exact Change', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Travel', role: 'Angry Conductor', desc: 'Fight to get your 200 Naira change before the conductor jumps back on the moving bus.' },
  { id: 'et3-03', title: 'POS Decline', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Shopping', role: 'Supermarket Cashier', desc: 'Show your debit alert to prove you paid, even though the POS machine said "Declined."' },
  { id: 'et3-05', title: 'NYSC Biometric Failure', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Work', role: 'LGI', desc: 'Plead with your Local Government Inspector because the fingerprint scanner refuses to read your thumb.' },
  { id: 'et3-06', title: 'Omo-Onile Demand', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Incidents', role: 'Street Thug', desc: 'Refuse to pay a random "parking fee" to a guy standing next to an empty piece of dirt.' },
  { id: 'et3-08', title: 'Generator Noise Complaint', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Everyday', role: 'Stubborn Neighbor', desc: 'Beg your neighbor to turn off their massive, smoky diesel generator at 3 AM.' },
  { id: 'et3-09', title: 'Amala Joint VIP', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Dining', role: 'Bukka Server', desc: 'Demand preferential treatment and extra assorted meat because you eat there every day.' },
  { id: 'et3-10', title: 'Data Bundle Vanishes', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Tech', role: 'Telecom Agent', desc: 'Yell at customer care because your 20GB monthly data bundle disappeared in three hours.' },
  { id: 'et3-11', title: 'Fake Prophet', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Everyday', role: 'Street Preacher', desc: 'Politely decline an unsolicited "vision" about your future from a random street pastor.' },
  { id: 'et3-12', title: 'The Wedding Rice Pack', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Dining', role: 'Strict Caterer', desc: 'Argue that you definitely know the groom and deserve a takeaway pack of Jollof.' },
  { id: 'et3-13', title: 'Bank Reversal Delay', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Work', role: 'Bank Teller', desc: 'Demand a timeline for a failed transfer reversal that has been pending for two weeks.' },
  { id: 'et3-14', title: 'Mechanic Stories', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Incidents', role: 'Local Mechanic', desc: 'Listen to a wild excuse about why your car engine is now making a completely different noise.' },
  { id: 'et3-15', title: 'Tailor Disappointment', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Everyday', role: 'Fashion Tailor', desc: 'Complain that the outfit they sewed looks absolutely nothing like the picture you gave them.' }
];