import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packPapaScenarios: ScenarioType[] = [
  { id: 'pap-01', title: 'Fake Cosplay Props', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English', 'Mandarin'], category: 'Pop Culture', role: 'Convention Security', desc: 'Argue that your 6-foot Buster Sword is made of foam and not an actual lethal weapon.' },
  { id: 'pap-02', title: 'Gacha Pity System', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Gaming', role: 'Smug Friend', desc: 'Complain that you hit hard pity in Zenless Zone Zero and still lost the 50/50.' },
  { id: 'pap-03', title: 'Campers in Blood Strike', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English', 'Spanish'], category: 'Gaming', role: 'Enemy Sniper', desc: 'Trash talk a player who has been hiding in the same tower for the entire match.' },
  { id: 'pap-04', title: 'Manga Spoilers in Line', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Everyday', role: 'Loud Otaku', desc: 'Yell at someone in the convention line for loudly discussing the ending of Chainsaw Man.' },
  { id: 'pap-05', title: 'Warframe Trading Scam', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Gaming', role: 'Shady Trader', desc: 'Call out a player in the Warframe trade chat trying to overcharge you for a vaulted Prime blueprint.' },
  { id: 'pap-06', title: 'Webtoon Translation Debate', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English', 'Korean'], category: 'Pop Culture', role: 'Scanlation Group Admin', desc: 'Argue over the accurate translation of a specific martial arts technique in Nano Machine.' },
  { id: 'pap-07', title: 'Combat Master Cheater', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Gaming', role: 'Server Admin', desc: 'Submit a highly detailed report explaining why the enemy team is definitely using aimbots.' },
  { id: 'pap-08', title: 'Buying Overpriced Figures', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Shopping', role: 'Merch Booth Vendor', desc: 'Haggle over the ridiculous markup on an imported anime scale figure.' },
  { id: 'pap-09', title: 'Stuck on the Final Boss', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Gaming', role: 'Twitch Chat (Hivemind)', desc: 'Beg your livestream chat for advice after dying to the same boss 47 times.' },
  { id: 'pap-10', title: 'The D&D Min-Maxer', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Everyday', role: 'Frustrated Dungeon Master', desc: 'Defend your incredibly broken, rule-bending character build to your Dungeon Master.' },
  { id: 'pap-11', title: 'Stolen Kill', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Gaming', role: 'Squadmate', desc: 'Yell at your teammate for stealing your execution after you did 99% of the damage.' },
  { id: 'pap-12', title: 'Lost Save File', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Gaming', role: 'Younger Sibling', desc: 'Interrogate your sibling who accidentally overwrote your 150-hour RPG save file.' },
  { id: 'pap-13', title: 'Con-Plague Symptoms', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Incidents', role: 'Pharmacist', desc: 'Describe your terrible cold symptoms after attending a massive 3-day anime convention.' },
  { id: 'pap-14', title: 'Selling Retro Games', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Shopping', role: 'Pawn Shop Owner', desc: 'Refuse to sell your mint-condition Pokémon Fire Red cartridge for pennies.' },
  { id: 'pap-15', title: 'Lore Inaccuracy', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Pop Culture', role: 'Casual Fan', desc: 'Aggressively correct a friend who got the overarching lore of the BlueString universe completely wrong.' }
];