import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packWhiskeyTwoScenarios: ScenarioType[] = [
  { id: 'wkw-01', title: 'Splitting the Check', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Dining', role: 'Your Date', desc: 'Navigate the extremely awkward conversation of splitting a very expensive dinner bill.' },
  { id: 'wkw-02', title: 'Anime Lore on a First Date', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Everyday', role: 'Confused Date', desc: 'Realize you just spent 45 minutes explaining the Murim timeline instead of asking about them.' },
  { id: 'wkw-03', title: 'Running into an Ex', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Everyday', role: 'Your Ex', desc: 'Try to act completely natural while running into your ex at a tiny coffee shop.' },
  { id: 'wkw-04', title: 'Card Declined on a Date', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Incidents', role: 'Waiter', desc: 'Loudly explain to the waiter that your bank must have placed a fraud alert on your card.' },
  { id: 'wkw-05', title: 'The Catfish', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Everyday', role: 'Tinder Date', desc: 'Politely point out that they look absolutely nothing like their 10-year-old profile pictures.' },
  { id: 'wkw-06', title: 'Allergic to their Pet', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Everyday', role: 'Proud Cat Owner', desc: 'Try to hide the fact that their apartment full of cats is sending you into anaphylactic shock.' },
  { id: 'wkw-07', title: 'Parents Walk In', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Everyday', role: 'Strict Father', desc: 'Explain to her father why you are both sitting in the dark watching Chainsaw Man.' },
  { id: 'wkw-08', title: 'Wrong Restaurant', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Dining', role: 'Your Date', desc: 'Call your date to explain you are sitting at the downtown location, and they are at the uptown one.' },
  { id: 'wkw-09', title: 'Overdressed', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Everyday', role: 'Casual Date', desc: 'Explain why you showed up in a full three-piece suit to a casual dive bar.' },
  { id: 'wkw-10', title: 'Spilled Drink on Date', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Incidents', role: 'Your Date', desc: 'Apologize for knocking a full glass of water directly into their lap.' },
  { id: 'wkw-11', title: 'The Interrogation', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Everyday', role: 'Overprotective Sibling', desc: 'Survive a barrage of intense questions from your date\'s older sibling before the date even starts.' },
  { id: 'wkw-12', title: 'Forgot Your Wallet', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Incidents', role: 'Annoyed Date', desc: 'Confess that you left your wallet in your other jacket and ask if they can cover the movie tickets.' },
  { id: 'wkw-13', title: 'The Terrible Joke', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Everyday', role: 'Unamused Date', desc: 'Try to recover the conversation after telling a joke that landed horribly.' },
  { id: 'wkw-14', title: 'Crying at a Movie', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Everyday', role: 'Your Date', desc: 'Defend why you are uncontrollably sobbing at the end of an animated film.' },
  { id: 'wkw-15', title: 'The Ex Texts', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Incidents', role: 'Suspicious Date', desc: 'Explain why your phone screen just lit up with a message from "My Ex" while on the table.' }
];