import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packFoxtrotTwoScenarios: ScenarioType[] = [
  { id: 'ftw-01', title: 'Dark Souls Invasion', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Gaming', role: 'Invader', desc: 'Message a player who invaded your game, bowed respectfully, and then immediately backstabbed you.' },
  { id: 'ftw-02', title: 'Anime Filler Rant', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Pop Culture', role: 'Casual Viewer', desc: 'Explain why someone absolutely must skip the 100-episode filler arc to understand the main plot.' },
  { id: 'ftw-03', title: 'Scalped Tickets', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Shopping', role: 'Ticket Scalper', desc: 'Argue with a scalper who is trying to sell a $50 concert ticket for $800.' },
  { id: 'ftw-04', title: 'Backseat Gaming', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Gaming', role: 'Annoying Sibling', desc: 'Yell at your sibling who keeps telling you exactly how to play a game they have never touched.' },
  { id: 'ftw-05', title: 'Defending a Terrible Movie', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Pop Culture', role: 'Film Critic Friend', desc: 'Argue that a universally hated superhero movie is actually an unappreciated masterpiece.' },
  { id: 'ftw-06', title: 'Rolling a Natural 1', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Everyday', role: 'Dungeon Master', desc: 'Beg the DM to let you reroll after a natural 1 causes your character to throw their sword into a river.' },
  { id: 'ftw-07', title: 'Broken Controller Excuse', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Gaming', role: 'Smug Winner', desc: 'Insist that you only lost the fighting game tournament because your controller has input lag.' },
  { id: 'ftw-08', title: '3-Hour Lore Dump', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Pop Culture', role: 'Exhausted Friend', desc: 'Try to continue explaining the deep lore of your favorite fantasy series even though they stopped listening an hour ago.' },
  { id: 'ftw-09', title: 'Gatekeeping a Band', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Everyday', role: 'Hipster', desc: 'Argue with a hipster who claims you aren\'t a "real fan" because you only know their most popular song.' },
  { id: 'ftw-10', title: 'Corrupted Save Data', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Gaming', role: 'Tech Support', desc: 'Cry to PlayStation support because a power outage corrupted your 200-hour Elden Ring save.' },
  { id: 'ftw-11', title: 'Toxic Voice Chat', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Gaming', role: '12-Year-Old Gamer', desc: 'Argue back against a squeaker who is trash-talking you in a Call of Duty lobby.' },
  { id: 'ftw-12', title: 'Gacha Whale Regrets', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Gaming', role: 'Financial Advisor', desc: 'Explain to your accountant why you spent $2,000 on digital anime characters this month.' },
  { id: 'ftw-13', title: 'Best Waifu Debate', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Pop Culture', role: 'Weeb Friend', desc: 'Aggressively debate why your favorite anime character is objectively the best.' },
  { id: 'ftw-14', title: 'Rage Quitting Monopoly', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Everyday', role: 'Smug Family Member', desc: 'Flip the board and explain why the rules of Monopoly are fundamentally unfair.' },
  { id: 'ftw-15', title: 'Manga Superiority', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Pop Culture', role: 'Anime-Only Fan', desc: 'Constantly interrupt the anime episode to explain how it was "done way better in the manga."' }
];