import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packEchoTwoScenarios: ScenarioType[] = [
  { id: 'ec2-01', title: 'Waving at Nobody', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Everyday', role: 'Confused Stranger', desc: 'Try to play it off after enthusiastically waving at someone who was actually waving to the person behind you.' },
  { id: 'ec2-02', title: 'Glass Door Collision', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Incidents', role: 'Concerned Bystander', desc: 'Act totally fine after walking face-first into a perfectly clean glass door.' },
  { id: 'ec2-03', title: 'Toilet Paper Shoe', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Everyday', role: 'Helpful Coworker', desc: 'React after a coworker points out you have a long strip of toilet paper stuck to your shoe.' },
  { id: 'ec2-04', title: 'Wrong Text Recipient', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Everyday', role: 'Your Boss', desc: 'Desperately explain why you just sent a text complaining about your boss... to your boss.' },
  { id: 'ec2-05', title: 'Forgot Name Mid-Sentence', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Everyday', role: 'Old Friend', desc: 'Try to introduce your friend to someone else while completely blanking on your friend\'s name.' },
  { id: 'ec2-06', title: 'The Fake Laugh', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Everyday', role: 'Chatty Acquaintance', desc: 'Admit you couldn\'t hear what they said after laughing and nodding at a question you didn\'t hear.' },
  { id: 'ec2-07', title: 'Accidental Video Call', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Tech', role: 'Confused Ex', desc: 'Explain that your phone unlocked in your pocket and you didn\'t mean to FaceTime them at 1 AM.' },
  { id: 'ec2-08', title: 'Loud Stomach', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Work', role: 'Interview Panel', desc: 'Apologize after your stomach violently growls during a moment of absolute silence in an interview.' },
  { id: 'ec2-09', title: 'Calling Teacher Mom', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Work', role: 'College Professor', desc: 'Try to recover after accidentally calling your professor "Mom" in front of a lecture hall.' },
  { id: 'ec2-10', title: 'Tripping Up Stairs', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Everyday', role: 'Onlooker', desc: 'Pretend you tripped on purpose to tie your shoe after falling UP a flight of stairs.' },
  { id: 'ec2-11', title: 'Unmuted Mic', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Work', role: 'HR Manager', desc: 'Apologize for loudly complaining about the meeting while your microphone was still unmuted.' },
  { id: 'ec2-12', title: 'Card Declined on Date', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Dining', role: 'Your Date', desc: 'Try to remain smooth while explaining to your date that your bank just froze your debit card.' },
  { id: 'ec2-13', title: 'Singing Wrong Lyrics', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Everyday', role: 'Music Snob', desc: 'Defend yourself after confidently belting out completely wrong lyrics at a concert.' },
  { id: 'ec2-14', title: 'Pushing a Pull Door', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Everyday', role: 'Store Clerk', desc: 'Apologize after aggressively pushing on a door marked "PULL" for solid 10 seconds.' },
  { id: 'ec2-15', title: 'Accidental "Love You"', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Work', role: 'Client', desc: 'Explain why you just ended a highly professional business phone call by saying "Love you, bye."' }
];