import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packSierraScenarios: ScenarioType[] = [
  { id: 'sie-01', title: 'BlueString Timeline', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English', 'Mandarin'], category: 'Pop Culture', role: 'YLAB Theorist', desc: 'Argue about the exact chronological overlap between Hanlim Gym and Study Group.' },
  { id: 'sie-02', title: 'Murim Clan Rankings', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English', 'Korean'], category: 'Pop Culture', role: 'Cultivation Master', desc: 'Debate why the Demonic Cult in Descent of the Demon God would easily crush orthodox sects.' },
  { id: 'sie-03', title: 'Anya\'s Telepathy', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Pop Culture', role: 'Spy x Family Fan', desc: 'Theorize what would happen if Loid found out about Anya\'s telepathy during a critical mission.' },
  { id: 'sie-04', title: 'Ragnarok Matchups', originalLanguage: 'German', availableLanguages: ['German', 'English', 'Japanese'], category: 'Pop Culture', role: 'Record of Ragnarok Fan', desc: 'Argue that a different historical figure should have fought in round 4.' },
  { id: 'sie-05', title: 'Goku vs Everyone', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English', 'Portuguese'], category: 'Pop Culture', role: 'Dragon Ball Scaler', desc: 'Aggressively defend Dragon Ball Super scaling against a fan of a different anime universe.' },
  { id: 'sie-06', title: 'Chainsaw Man Angst', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Pop Culture', role: 'Traumatized Manga Reader', desc: 'Complain about the latest brutal character death in Chainsaw Man.' },
  { id: 'sie-07', title: 'Absolute Sword Sense', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Pop Culture', role: 'Webtoon Critic', desc: 'Debate the pacing of the latest martial arts arc in Absolute Sword Sense.' },
  { id: 'sie-08', title: 'Invincible Mumu Feats', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Pop Culture', role: 'Power Scaler', desc: 'Argue about Mumu\'s raw physical strength compared to traditional Dantian users.' },
  { id: 'sie-09', title: 'Myst, Might, Mayhem', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Pop Culture', role: 'Lore Analyst', desc: 'Connect the hidden Easter eggs in Myst, Might, Mayhem to Han Joong Wueol Ya\'s other works.' },
  { id: 'sie-10', title: 'Reawakened Man Revival', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Pop Culture', role: 'Comic Fan', desc: 'Discuss the sheer chaotic absurdity of the revival mechanic in Reawakened Man.' },
  { id: 'sie-11', title: 'Spoiling the Ending', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Everyday', role: 'Loud Friend', desc: 'Yell at your friend for casually spoiling the ending of an anime you just started.' },
  { id: 'sie-12', title: 'Sub vs Dub Debate', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English', 'Japanese'], category: 'Pop Culture', role: 'Sub Elitist', desc: 'Defend your right to watch anime dubbed while gaming on your second monitor.' },
  { id: 'sie-13', title: 'Buying Fake Manga', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Shopping', role: 'Book Vendor', desc: 'Argue with a vendor selling poorly translated, counterfeit physical manga volumes.' },
  { id: 'sie-14', title: 'Cosplay Malfunction', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Incidents', role: 'Convention Staff', desc: 'Beg for safety pins and super glue after your armor completely falls apart.' },
  { id: 'sie-15', title: 'Anime Tattoo Concept', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Everyday', role: 'Tattoo Artist', desc: 'Try to explain a highly complex Murim cultivation symbol you want tattooed on your back.' }
];