import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packJulietThreeScenarios: ScenarioType[] = [
  { id: 'jt3-01', title: 'Next.js Hydration Error', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Tech', role: 'Frontend Engineer', desc: 'Stare in disbelief as a simple `div` mismatch completely breaks your Next.js hydration.' },
  { id: 'jt3-02', title: 'Cursor AI Infinite Loop', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Tech', role: 'Pair Programmer', desc: 'Yell at your AI assistant because it just generated an infinite loop that froze the browser.' },
  { id: 'jt3-03', title: 'Ubuntu GRUB Rescue', originalLanguage: 'German', availableLanguages: ['German', 'English'], category: 'Tech', role: 'Linux Admin', desc: 'Panic after a routine update dumps your Ubuntu 26 LTS installation straight into the GRUB rescue terminal.' },
  { id: 'jt3-04', title: 'Svelte Store Reactivity', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Tech', role: 'React Developer', desc: 'Try to explain the concept of `$state` runes to a developer who is obsessed with React hooks.' },
  { id: 'jt3-05', title: 'Vercel 502 Bad Gateway', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Tech', role: 'Impatient Client', desc: 'Frantically refresh the Vercel dashboard because your live production site just threw a 502 error.' },
  { id: 'jt3-06', title: 'Tailwind Arbitrary Values', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Tech', role: 'UI Designer', desc: 'Defend your decision to use `w-[14.53rem]` instead of updating the core configuration file.' },
  { id: 'jt3-07', title: 'C++ Segmentation Fault', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Tech', role: 'Engine Developer', desc: 'Debug a memory leak that is causing a segmentation fault every time you run the Trauma Engine.' },
  { id: 'jt3-08', title: 'SQLite Concurrent Write', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Tech', role: 'DBA', desc: 'Explain to a Voix Network user that they cannot save their ticket because the database is currently locked.' },
  { id: 'jt3-09', title: 'Rclone Auth Expiration', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Tech', role: 'Cloud Admin', desc: 'Realize your automated backups have been failing for three weeks because the OneDrive token expired.' },
  { id: 'jt3-10', title: 'Git Merge Conflict', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Tech', role: 'Teammate', desc: 'Complain that your colleague completely overwrote your `index.ts` file during a reckless Git merge.' },
  { id: 'jt3-11', title: 'Node Modules Black Hole', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Tech', role: 'Hardware Monitor', desc: 'Explain why a single web project is taking up 4GB of your SSD space.' },
  { id: 'jt3-12', title: 'PipeWire Bluetooth Profile', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Tech', role: 'Audiophile', desc: 'Troubleshoot why Ubuntu keeps defaulting your high-end headset to the terrible Hands-Free Audio profile.' },
  { id: 'jt3-13', title: 'Docker Volume Permission', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English'], category: 'Tech', role: 'DevOps', desc: 'Argue with a Docker container that refuses to write to a mounted volume because of a root permission mismatch.' },
  { id: 'jt3-14', title: 'Nginx Reverse Proxy', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Tech', role: 'Sysadmin', desc: 'Try to figure out why Nginx is forwarding all traffic to the wrong internal port on the server.' },
  { id: 'jt3-15', title: 'Vite HMR Broken', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Tech', role: 'Frontend Dev', desc: 'Refresh the browser manually 50 times because Hot Module Replacement completely stopped working.' }
];