import { ALL_LANGUAGES, type ScenarioType } from './types';

export const packJulietTwoScenarios: ScenarioType[] = [
  { id: 'jtw-01', title: 'The Ruined Haircut', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English', 'French'], category: 'Everyday', role: 'Proud Barber', desc: 'Try to explain that the barber pushed your hairline way too far back without starting a fight.' },
  { id: 'jtw-02', title: 'Fake Designer Watch', originalLanguage: 'Mandarin', availableLanguages: ['Mandarin', 'English'], category: 'Shopping', role: 'Street Vendor', desc: 'Call out a vendor whose "Rolex" is ticking louder than a wall clock.' },
  { id: 'jtw-03', title: 'Stealing the Wi-Fi', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English'], category: 'Everyday', role: 'Cafe Owner', desc: 'Defend sitting in the cafe for 6 hours after only buying a single bottle of water.' },
  { id: 'jtw-04', title: 'Gym Equipment Hog', originalLanguage: 'German', availableLanguages: ['German', 'English', 'Russian'], category: 'Everyday', role: 'Influencer', desc: 'Ask them to move their tripod so you can actually use the dumbbells they are sitting on.' },
  { id: 'jtw-05', title: 'Spoiled Milk Reflex', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English'], category: 'Shopping', role: 'Grocery Manager', desc: 'Demand a refund after immediately throwing up in the parking lot from expired milk.' },
  { id: 'jtw-06', title: 'The Double Charge', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Shopping', role: 'Bartender', desc: 'Show your banking app proving you were charged twice for the same round of drinks.' },
  { id: 'jtw-07', title: 'Awkward Elevator Ride', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Everyday', role: 'Chatty Neighbor', desc: 'Try to give one-word answers to someone who wants to know your entire life story.' },
  { id: 'jtw-08', title: 'Borrowing Tools Forever', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Everyday', role: 'Forgetful Neighbor', desc: 'Demand your power drill back after they "borrowed" it for six months.' },
  { id: 'jtw-09', title: 'The Overselling Salesman', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English'], category: 'Shopping', role: 'Car Salesman', desc: 'Firmly state you only want the base model and absolutely no extended warranties.' },
  { id: 'jtw-10', title: 'Ruining the Surprise', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'English'], category: 'Everyday', role: 'Angry Partner', desc: 'Try to act surprised after accidentally finding the receipt for your own birthday gift.' },
  { id: 'jtw-11', title: 'Noisy Theater Eaters', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Everyday', role: 'Crunchy Eater', desc: 'Ask the person behind you if they can chew their extremely loud chips with their mouth closed.' },
  { id: 'jtw-12', title: 'Stealing the Cab', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Incidents', role: 'Rival Pedestrian', desc: 'Argue in the pouring rain over who actually hailed the taxi first.' },
  { id: 'jtw-13', title: 'The Guilt Trip Tip', originalLanguage: 'English', availableLanguages: ALL_LANGUAGES, category: 'Dining', role: 'Barista with an iPad', desc: 'Stare them down while hitting the "No Tip" button for a $6 black coffee.' },
  { id: 'jtw-14', title: 'Returning a Dead Fish', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Shopping', role: 'Pet Store Owner', desc: 'Try to get a refund for a goldfish that went belly-up the second you put it in the tank.' },
  { id: 'jtw-15', title: 'The Fake VIP', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English'], category: 'Everyday', role: 'Bouncer', desc: 'Pretend you are a famous music producer named John Hizaki to skip the line.' }
];