import { ALL_LANGUAGES, type ScenarioType } from './types';

export const travelScenarios: ScenarioType[] = [
  // TRAVEL
  { id: 'trv-tokyo-hotel', title: 'Checking into a Tokyo Hotel', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'Korean', 'English', 'Mandarin'], category: 'Travel', role: 'Hotel Receptionist', desc: 'You are checking into your Shinjuku hotel earlier than the check-in time.' },
  { id: 'trv-berlin-train', title: 'Missed Train in Berlin', originalLanguage: 'German', availableLanguages: ALL_LANGUAGES, category: 'Travel', role: 'Ticket Inspector', desc: 'You boarded the wrong ICE train and need to explain your situation.' },
  { id: 'trv-seoul-taxi', title: 'Lost in Seoul', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English'], category: 'Travel', role: 'Taxi Driver', desc: 'Give a taxi driver directions to your Airbnb without knowing the exact address.' },
  { id: 'trv-lagos-danfo', title: 'Danfo Bus Wahala', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Travel', role: 'Bus Conductor', desc: 'Argue with the conductor who refuses to give you your exact change.' },
  { id: 'trv-dubai-layover', title: 'Flight Delay Compensation', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English', 'Hindi', 'Urdu'], category: 'Travel', role: 'Airline Rep', desc: 'Request a hotel voucher after your connecting flight was delayed 12 hours.' },
  { id: 'trv-venice-gondola', title: 'Negotiating a Ride', originalLanguage: 'Italian', availableLanguages: ['Italian'], category: 'Travel', role: 'Gondolier', desc: 'Ask for a 30-minute tour route and confirm the fixed price.' },
  { id: 'trv-amsterdam-bike', title: 'Renting a Bicycle', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English', 'German'], category: 'Travel', role: 'Bike Shop Owner', desc: 'Ask for a daily rental rate and a heavy-duty lock.' },
  { id: 'trv-mumbai-train', title: 'Rush Hour in Mumbai', originalLanguage: 'Hindi', availableLanguages: ['Hindi', 'English'], category: 'Travel', role: 'Station Master', desc: 'Ask which platform the fast train to Churchgate is arriving on.' },
  { id: 'trv-paris-metro', title: 'Metro Turnstile Error', originalLanguage: 'French', availableLanguages: ALL_LANGUAGES, category: 'Travel', role: 'Station Attendant', desc: 'Your ticket was eaten by the machine and you are stuck behind the turnstile.' },
  { id: 'trv-rio-bus', title: 'Taking the Wrong Bus', originalLanguage: 'Portuguese', availableLanguages: ['Portuguese', 'Spanish', 'English'], category: 'Travel', role: 'Fellow Passenger', desc: 'Ask a passenger if this bus is going to Copacabana or if you are lost.' },
  { id: 'trv-moscow-subway', title: 'Navigating the Metro', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Travel', role: 'Local Commuter', desc: 'Ask a local which train line goes to the Red Square.' },
  { id: 'trv-istanbul-ferry', title: 'Bosphorus Ferry Commute', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'English', 'Arabic'], category: 'Travel', role: 'Ferry Attendant', desc: 'Try to buy a tea and a simit while the ferry rocks violently.' },
  { id: 'trv-london-tube', title: 'Oyster Card Issues', originalLanguage: 'English', availableLanguages: ['English', 'French', 'Hindi'], category: 'Travel', role: 'TfL Worker', desc: 'Explain that the gate charged you maximum fare because you forgot to tap out.' },
  { id: 'trv-madrid-rental', title: 'Renting a Car', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'Portuguese', 'Italian', 'German', 'English'], category: 'Travel', role: 'Rental Agent', desc: 'Decline extra insurance while picking up your rental car.' },
  
  // DINING
  { id: 'din-paris-coffee', title: 'Ordering Coffee in Paris', originalLanguage: 'French', availableLanguages: ['French', 'Spanish', 'English', 'German', 'Italian'], category: 'Dining', role: 'Parisian Barista', desc: 'Order a coffee and a pastry at a busy local cafe in Paris.' },
  { id: 'din-naples-pizza', title: 'Customizing a Pizza', originalLanguage: 'Italian', availableLanguages: ALL_LANGUAGES, category: 'Dining', role: 'Pizzaiolo', desc: 'Order a Margherita pizza but ask for half of it to have spicy salami.' },
  { id: 'din-osaka-izakaya', title: 'Ordering Drinks & Skewers', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English', 'Korean'], category: 'Dining', role: 'Izakaya Waiter', desc: 'Order a round of beers and ask for the chefs recommended yakitori.' },
  { id: 'din-istanbul-kebab', title: 'Spicy Level Request', originalLanguage: 'Turkish', availableLanguages: ['Turkish', 'Arabic', 'English'], category: 'Dining', role: 'Street Vendor', desc: 'Order a doner kebab and ask for it to be extra, extra spicy.' },
  { id: 'din-seoul-bbq', title: 'Grill Change Request', originalLanguage: 'Korean', availableLanguages: ['Korean', 'English', 'Japanese'], category: 'Dining', role: 'Server', desc: 'Ask the server to change the burnt grill pan and order more soju.' },
  { id: 'din-buenos-aires', title: 'Sending Food Back', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'English', 'Portuguese'], category: 'Dining', role: 'Waiter', desc: 'Politely explain that your steak is well-done instead of medium-rare.' },
  { id: 'din-bukka-joint', title: 'Ordering Amala', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English'], category: 'Dining', role: 'Bukka Attendant', desc: 'Order Amala and Ewedu, demanding extra assorted meat.' },
  { id: 'din-delhi-streetfood', title: 'Too Much Spice', originalLanguage: 'Hindi', availableLanguages: ALL_LANGUAGES, category: 'Dining', role: 'Chaat Vendor', desc: 'Desperately ask for water or yogurt because the pani puri was way too spicy.' },
  { id: 'din-moscow-blini', title: 'Ordering Blini', originalLanguage: 'Russian', availableLanguages: ['Russian', 'English'], category: 'Dining', role: 'Kiosk Worker', desc: 'Order pancakes with caviar and sour cream during a freezing winter day.' },
  { id: 'din-amsterdam-stroop', title: 'Fresh Stroopwafels', originalLanguage: 'Dutch', availableLanguages: ['Dutch', 'English'], category: 'Dining', role: 'Market Baker', desc: 'Order a massive, warm stroopwafel and ask them not to skimp on the caramel.' },
  { id: 'din-ny-deli', title: 'The Complicated Order', originalLanguage: 'English', availableLanguages: ['English', 'Spanish'], category: 'Dining', role: 'Deli Worker', desc: 'Order a highly specific, customized bagel sandwich during the morning rush.' },

  // SHOPPING
  { id: 'shp-mexico-market', title: 'Haggling in Mexico City', originalLanguage: 'Spanish', availableLanguages: ['Spanish', 'Portuguese', 'English'], category: 'Shopping', role: 'Market Vendor', desc: 'Negotiate the price of a beautiful handmade blanket.' },
  { id: 'shp-tokyo-camera', title: 'Buying a Camera', originalLanguage: 'Japanese', availableLanguages: ['Japanese', 'English', 'Mandarin'], category: 'Shopping', role: 'Electronics Store Staff', desc: 'Ask if the warranty on a mirrorless camera is valid internationally.' },
  { id: 'shp-dubai-gold', title: 'Gold Souk Negotiation', originalLanguage: 'Arabic', availableLanguages: ['Arabic', 'English', 'Hindi'], category: 'Shopping', role: 'Jeweler', desc: 'Ask about the karat purity and negotiate the making charge of a necklace.' },
  { id: 'shp-berlin-flea', title: 'Haggling for Antiques', originalLanguage: 'German', availableLanguages: ALL_LANGUAGES, category: 'Shopping', role: 'Antique Dealer', desc: 'Negotiate the price of a vintage typewriter at the Mauerpark flea market.' },
  { id: 'shp-computer-village', title: 'Buying a Used Laptop', originalLanguage: 'Pidgin English', availableLanguages: ['Pidgin English', 'English'], category: 'Shopping', role: 'Tech Vendor', desc: 'Test a used laptop and haggle over the battery health.' },
  { id: 'shp-paris-pharmacy', title: 'Buying Skincare', originalLanguage: 'French', availableLanguages: ['French', 'English'], category: 'Shopping', role: 'Pharmacist', desc: 'Ask for the best moisturizer for sensitive skin.' },
  { id: 'shp-milan-fashion', title: 'Trying on Clothes', originalLanguage: 'Italian', availableLanguages: ['Italian', 'English', 'French', 'Mandarin'], category: 'Shopping', role: 'Boutique Clerk', desc: 'Ask for a different size and color for a jacket you want to try on.' },
  { id: 'shp-seoul-skincare', title: 'Skincare Routine', originalLanguage: 'Korean', availableLanguages: ['Korean', 'Mandarin', 'Japanese', 'English'], category: 'Shopping', role: 'Beauty Consultant', desc: 'Ask for recommendations for dry, sensitive skin products.' }
];